### PR TITLE
Static nat form

### PR DESCRIPTION
**Pull request by RitchieVincent**

### CODE REVIEW

**Comment by rhtyd** [comment]
@RitchieVincent can you merge latest master and check that when static nat is enabled for an IP; then only firewall tab must be shown.

**Comment by RitchieVincent** [comment]
> @RitchieVincent can you merge latest master and check that when static nat is enabled for an IP; then only firewall tab must be shown.

Will do now 👍

**Comment by RitchieVincent** [comment]
@rhtyd Only the firewall tab will show if Static NAT is enabled now.

**Comment by rhtyd** [comment]
Thanks @RitchieVincent will review now

**Pull request merged**
