### PR TITLE
Hide root disk controller, nic adapter and guest OS when registering deploy as is template

### PR DESCRIPTION
**Pull request by nvazquez**
Deploy as is template must not allow selecting:
- Root disk controller
- NIC adapter type
- Guest OS

That information is obtained from the OVF as-is

image

### CODE REVIEW

**Comment by rhtyd** [comment]
LGTM
Need second pair of eyes, @davidjumani can you review this?
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
Changes LGTM. @andrijapanicsb Could you test it ?

**Comment by rhtyd** [comment]
LGTM @andrijapanicsb can you test latest master now, thnx

**Comment by andrijapanicsb** [comment]
LGTM

(though it is just a partial solution - hiding those while regiostering template, but can be added later in tempalte/VM details etc.)

**Pull request merged**
