### PR TITLE
Hide status column for users other than Root admin

### PR DESCRIPTION
**Pull request by Pearl1594**
This attempts to fix hiding the status column for users other than Root Admins for templates and ISOs not owned by it.
Addresses: https://github.com/apache/cloudstack-primate/issues/476

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Please review @davidjumani

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
