### PR TITLE
Domain admin: Accounts > selected - settings should not be visible

### PR DESCRIPTION
**Pull request by utchoang**
Fixes https://github.com/apache/cloudstack-primate/issues/237

### CODE REVIEW

**Comment by utchoang** [comment]
* Domain admin/user
image

image

* Admin
image

image

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel 
I've completed. Please review and let me know your comments.

**Comment by shwstppr** [comment]
@rhtyd ready for review

**Comment by rhtyd** [comment]
Didn't test it.

**Pull request merged**
