### PR TITLE
offerings: Removing tags for offerings

### PR DESCRIPTION
**Pull request by davidjumani**
Removing tags from offerings as they do not support them

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani please check against old UI, while we may not support this in UI - the API supports the tags parameter

**Comment by ravening** [comment]
@davidjumani sometimes we do use tags for offerings to manage vm deployments and vm migrations depending on offering and host tags. So removing may not be a good idea

**Comment by rhtyd** [comment]
@ravening are you okay with latest changes?
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
We need one additional review, pinging @utchoang @Pearl1594 thanks.

**Comment by davidjumani** [comment]
It doesn't show / add tags in the project view, but can in the default view (only for vpc offerings). Adding resourcetype for vpc offerings. Will need another PR to handle it in case of projects

**Comment by davidjumani** [comment]
@blueorangutan package

**Pull request merged**
