### PR TITLE
Fixing cks instance view

### PR DESCRIPTION
**Pull request by davidjumani**
UI fix for https://github.com/apache/cloudstack/pull/4420
Also added a bunch of fixes

Screenshot from 2020-10-28 18-14-33

Screenshot from 2020-10-28 18-14-43

Screenshot from 2020-10-28 18-15-26
Screenshot from 2020-10-28 18-15-32
Screenshot from 2020-10-28 18-15-38
Screenshot from 2020-10-28 18-15-47

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by shwstppr — COMMENTED** [review]
@davidjumani NICs/IP addresses for VMs are not returned in listKubernetesCluster response. Showing empty in UI,
```
> list kubernetesclusters id=091c6924-b697-4517-96b0-52774b755742 
{
  "count": 1,
  "kubernetescluster": [
    {
      "account": "ACSUser",
      "associatednetworkname": "ut3-network",
      "cpunumber": "4",
      "description": "ut3",
      "domain": "ROOT",
      "domainid": "6cef5343-18f2-11eb-b801-1e00420139c1",
      "endpoint": "",
      "id": "091c6924-b697-4517-96b0-52774b755742",
      "kubernetesversionid": "951ef254-e002-4ffc-b3f3-57eed1409f4e",
      "kubernetesversionname": "v1.15.0",
      "masternodes": 1,
      "memory": "4096",
      "name": "ut3",
      "networkid": "7a00931f-5683-4c16-a476-9cceebe816a4",
      "serviceofferingid": "6b86c8ec-37c5-4cd0-b304-21a1b0c208ab",
      "serviceofferingname": "CKS Instance",
      "size": 1,
      "state": "Starting",
      "templateid": "a4ef4339-a447-44f5-baca-95762bd05178",
      "virtualmachines": [
        {
          "account": "ACSUser",
          "affinitygroup": [],
          "created": "2020-10-28T10:29:04+0000",
          "details": {
            "dataDiskController": "osdefault",
            "rootDiskController": "lsilogic"
          },
          "displayname": "ut3-master",
          "domain": "ROOT",
          "domainid": "6cef5343-18f2-11eb-b801-1e00420139c1",
          "guestosid": "6d1bea79-18f2-11eb-b801-1e00420139c1",
          "haenable": false,
          "hypervisor": "VMware",
          "id": "10aabe3c-6d88-4bbe-a7d8-601b70199d29",
          "isdynamicallyscalable": false,
          "name": "ut3-master",
          "nic": [],
          "osdisplayname": "Other Linux (64-bit)",
          "ostypeid": "6d1bea79-18f2-11eb-b801-1e00420139c1",
          "readonlyuidetails": "dataDiskController, rootDiskController",
          "securitygroup": [],
          "state": "Running",
          "tags": [],
          "userid": "31367125-7983-4f32-ae09-dc41cc2c8174",
          "username": "user",
          "zoneid": "cff0423f-76f4-40fb-bea8-95ecdfc004cc",
          "zonename": "pr4131-t3091-vmware-67u3"
        },
        {
          "account": "ACSUser",
          "affinitygroup": [],
          "created": "2020-10-28T10:29:37+0000",
          "details": {
            "dataDiskController": "osdefault",
            "rootDiskController": "lsilogic"
          },
          "displayname": "ut3-node-1",
          "domain": "ROOT",
          "domainid": "6cef5343-18f2-11eb-b801-1e00420139c1",
          "guestosid": "6d1bea79-18f2-11eb-b801-1e00420139c1",
          "haenable": false,
          "hypervisor": "VMware",
          "id": "e11a4329-1cf6-4c0a-aab2-7cef325a1069",
          "isdynamicallyscalable": false,
          "name": "ut3-node-1",
          "nic": [],
          "osdisplayname": "Other Linux (64-bit)",
          "ostypeid": "6d1bea79-18f2-11eb-b801-1e00420139c1",
          "readonlyuidetails": "dataDiskController, rootDiskController",
          "securitygroup": [],
          "state": "Running",
          "tags": [],
          "userid": "31367125-7983-4f32-ae09-dc41cc2c8174",
          "username": "user",
          "zoneid": "cff0423f-76f4-40fb-bea8-95ecdfc004cc",
          "zonename": "pr4131-t3091-vmware-67u3"
        }
      ],
      "zoneid": "cff0423f-76f4-40fb-bea8-95ecdfc004cc",
      "zonename": "pr4131-t3091-vmware-67u3"
    }
  ]
}
```

Screenshot from 2020-10-28 16-09-11
Should we remove IP address column?

**Comment by davidjumani** [comment]
@shwstppr Looks like an issue with the backend. Will look into it

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by shwstppr — APPROVED** [review]
LGTM, tested with k8s cluster on VMware env

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
