### PR TITLE
Fix create Zone

### PR DESCRIPTION
**Pull request by utchoang**
Open for https://github.com/apache/cloudstack-primate/issues/560#issuecomment-665540385 and https://github.com/apache/cloudstack-primate/issues/555#issuecomment-665540288
- [x] Add guest Vlan ID to network in Advanced Zone with SG enabled
- [x] Fix error from the console in the physical network step
- [x] Fix `Fix errors` button still present after fixing errors successfully

### CODE REVIEW

**Comment by utchoang** [comment]
* Add guest Vlan ID to network in Advanced Zone with SG enabled
Capture

* Hidden errors button after fixing
Capture2

**Comment by utchoang** [comment]
@davidjumani @rhtyd cc @svenvogel I've completed this task. Please review it. Thanks.

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@utchoang The fix errors button is still present even after the zone has been successfully created.
It should disappear and Launch Zone button should show instead to enable the newly created zone
Screenshot from 2020-07-30 10-24-26

**Comment by utchoang** [comment]
@davidjumani 
I think there was an underlying error at some steps. Can you give me the data step by step for me to test? Because the information needed to create a new zone I do not have.

**Comment by davidjumani** [comment]
@utchoang 
1. Select Advance Zone with SG Enabled
2. Enter Zone Details (only the mandatory fields : name, ipv4dns1, internaldns, simulator hypervisor)
3. Default physical network setup
4. Fill in random values for pod details
5. Fill in random values for guest network but **leave guest vlan blank**
6. Fill in random cluster, host, primary, secondary  storage details
7. Launch zone

You'll see errors in Guest Vlam
Click fix errors and now fill the guest vlan id
Now the zone will successfully be created but the Fix Errors button will still be seen

**Comment by utchoang** [comment]
@davidjumani I mean, the data to fill in the steps (network, host, storage, ...) so that running to the step is completed. 
Because I couldn't make it to the completed step, I couldn't get an error.

**Comment by davidjumani** [comment]
@utchoang looks like a db issue, Will restart and post screenshots

**Comment by davidjumani** [comment]
@utchoang 
Check of the following steps :
Screenshot from 2020-07-30 14-58-18
Screenshot from 2020-07-30 14-58-40
Screenshot from 2020-07-30 14-58-47
Screenshot from 2020-07-30 14-58-52
Screenshot from 2020-07-30 14-59-21
NOTE : Leave VLAN ID blank at this stage. We'll come back to fix it later
Screenshot from 2020-07-30 15-00-41
Screenshot from 2020-07-30 15-00-48
Screenshot from 2020-07-30 15-01-10
Screenshot from 2020-07-30 15-01-49
Screenshot from 2020-07-30 15-02-07
Screenshot from 2020-07-30 15-02-12
Screenshot from 2020-07-30 15-02-41
Go back and set a VLAN now
Screenshot from 2020-07-30 15-02-50
Screenshot from 2020-07-30 15-02-58
The fix errors button is still visible
Screenshot from 2020-07-30 15-03-14
Some other errors thats seen
Screenshot from 2020-07-30 15-03-36

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@davidjumani I've fixed it. Thanks.
Capture
Capture4

**Pull request merged**
