### PR TITLE
IP Ranges form component for Public, Management and Storage traffic types

### PR DESCRIPTION
**Pull request by RitchieVincent**

### CODE REVIEW

**Comment by RitchieVincent** [comment]
@rhtyd Quick note about this, I had to change the vertical nav links to horizontal cards, as they would not display on mobile nicely. This also had the added benefit of allowing more width in the display area.

**Comment by rhtyd** [comment]
@RitchieVincent for the public network IP range, can you show the domain/account reservation form in the main modal itself than the modal-in-a-modal format:

Screenshot from 2020-02-03 17-41-33

For example, use a radio button to show/hide whether admin wants reservation or not.

**Comment by RitchieVincent** [comment]
> @RitchieVincent for the public network IP range, can you show the domain/account reservation form in the main modal itself than the modal-in-a-modal format:
> 
> Screenshot from 2020-02-03 17-41-33
> 
> For example, use a radio button to show/hide whether admin wants reservation or not.

That's sorted now in the latest updates to this PR.

**Comment by rhtyd** [comment]
@RitchieVincent can you make use of `a-table` with pagination in this PR as well?

**Comment by RitchieVincent** [comment]
> @RitchieVincent can you make use of `a-table` with pagination in this PR as well?

That's complete now in the latest PR.

**Pull request merged**
