### PR TITLE
Creating custom form to delete vm

### LINKED ISSUE #477: [BUG] Prompt regarding Data Volumes shown when destroying a VM is misleading
**Describe the bug**

When destroying an instance the user should be shown any data disks attached and given the option to delete them.

**To Reproduce**
1. Create a VM (without a data disk)
2. Click on 'Destroy' the VM 
3. See the prompt (compare to Legacy UI)

**Expected behavior**

The prompt should read 'Data Volumes to be deleted:'  (incorrect mapping used - should be "label.delete.volumes")
When there are no Data volumes attached, the label "label.volume.empty" should be used ("No data volumes attached to this VM")

**Screenshots**

Primate:
image
Legacy:
image

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #477 

Screenshot from 2020-07-01 12-07-51
Screenshot from 2020-07-01 12-08-58

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd Good to go!

**Comment by rhtyd** [comment]
This breaks group actions, when multiple VMs are selected in list view - the first non-selected item is picked and deleted :( instead of selected ones other LGTM

**Pull request merged**
