### PR TITLE
views: create network action

### PR DESCRIPTION
**Pull request by shwstppr**
Adds custom create network action.

- [x] Isolated network
- [x] L2 network
- [x] Shared network

Screenshot from 2020-03-05 13-35-52
Screenshot from 2020-03-05 13-36-06
Screenshot from 2020-03-05 13-36-22

### CODE REVIEW

**Comment by rhtyd** [comment]
@shwstppr is it complete, ready for review/testing? If not can you ping me when it is?

**Comment by shwstppr** [comment]
@rhtyd sure, will update you once ready. Later today or tomorrow morning.

**Comment by rhtyd** [comment]
@shwstppr general notes: 
- Avoid using `this.$t()` withing `<template>...`, just use `$t(...)`
- For translation, simply use the API arg such as `zoneid`, instead of `label.zoneid` (we'll fix this to make translation keys consistent)
- The tabbed layout makes the UI form wobbly, as switching between forms (with different heights), let's discuss later how this jumpy behaviour can be fixed

**Comment by shwstppr** [comment]
> @shwstppr general notes:
> 
>     * Avoid using `this.$t()` withing `<template>...`, just use `$t(...)`
> 
>     * For translation, simply use the API arg such as `zoneid`, instead of `label.zoneid` (we'll fix this to make translation keys consistent)
> 
>     * The tabbed layout makes the UI form wobbly, as switching between forms (with different heights), let's discuss later how this jumpy behaviour can be fixed

Except for tabbed UI rest of the functionality should be fine now. @rhtyd

**Comment by rhtyd** [comment]
@shwstppr can you review this, address all the label/issues; we want to prefer using the API arg as the translatable string. Ping me when this is ready for review, thanks.

**Comment by shwstppr** [comment]
@rhtyd addressed label. issue.
Actually it was addressed earlier itself, only the screenshots were old.

**Comment by rhtyd** [comment]
LGTM but requires fixes for shared network:
- non-shared network offerings listed
- dont' show the secondary vlan id, but show the dropdown and show only when one of the community/isolated selected
- project scope returns exception
@shwstppr

**Comment by shwstppr** [comment]
@rhtyd  addressed issues

**Pull request merged**
