### PR TITLE
Create new view component for Tree Domain

### PR DESCRIPTION
**Pull request by utchoang**
Restructuring the Tree Domain avoids unnecessary dependencies in AutogenView

### CODE REVIEW

**Comment by utchoang** [comment]
Hi @rhytd. I completed fixed it. Please review and let me know your comments.

**Comment by rhtyd** [comment]
@utchoang can you rebase against latest master, check/fix the conflict and the feature? Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you merge the conflict, thanks.

**Comment by rhtyd** [comment]
@utchoang can you merge the conflict, thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you address following:
- Navigation from a different view does not show the domain tab with info card and comments (to reproduce goto account and click on domain "ROOT" for example)
Screenshot from 2020-06-16 12-50-30
- When navigating from a different view, it does not show/select the domain (use primate-qa server, go to accounts tab and say select "ROOT/saml" domain, on the left side of the tree-view still the "ROOT"domain is selected)
- Perhaps for the resource view we can still use autogen-view but use the new component only for listView; for example when selecting a domain, we can show the view like:
Screenshot from 2020-06-16 12-53-50

**Comment by utchoang** [comment]
@rhtyd  Thank you for the feedback. I have edited the following: When navigating from a different view, I will use a view like AutogenView (bellow image). 
image

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
