### PR TITLE
Add support to manage network service providers

### LINKED ISSUE #250: [FEATURE] Add support to manage network service providers
For technical preview, only limited network service providers are supported. We list all the available providers but don't allow other features such as to manage/add/edit/update and perform other operations on network service providers that use APIs that have keywords:
 cisco, nicira, baremetal, srx, f5, brocade, palo, ucs, netscaler, bigswitch, ovs, globalloadbalancer, opendaylight etc.

For example the list of NSPs (network service providers) can be seen in old UI -> Infra -> Zone -> Physical network -> select a physical network -> network service providers:
Screenshot from 2020-03-23 22-23-27

When we click on any of the service providers we can see some new buttons and link to list the devices etc. For example this is what we see for Netscalar:
Screenshot from 2020-03-23 22-23-44

The requirements of this task are:
- Add support for all the network service providers which are not already supported
- Each NSP must be implemented in its separate component and imported and used here: https://github.com/apache/cloudstack-primate/blob/master/src/views/infra/network/ServiceProvidersTab.vue
- For each NSP component, add buttons and their forms in a modal and display a list of such NSP devices/resources in a table with pagination

For this task the following APIs (and few more) may need to be supported:
```
addBaremetalDhcp
addBaremetalPxeKickStartServer
addBaremetalRct
addCiscoAsa1000vResource
addCiscoVnmcResource
addNetscalerLoadBalancer
configureOvsElement
deleteBaremetalRct
deleteBigSwitchBcfDevice
deleteBrocadeVcsDevice
deleteCiscoAsa1000vResource
deleteCiscoNexusVSM
deleteCiscoVnmcResource
deleteF5LoadBalancer
deleteNetscalerControlCenter
deleteNetscalerLoadBalancer
deleteNiciraNvpDevice
deleteOpenDaylightController
deletePaloAltoFirewall
deleteSrxFirewall
disableCiscoNexusVSM
enableCiscoNexusVSM
listBaremetalDhcp
listBaremetalPxeServers
listBaremetalRct
listBigSwitchBcfDevices
listBrocadeVcsDevices
listCiscoAsa1000vResources
listCiscoNexusVSMs
listCiscoVnmcResources
listF5LoadBalancers
listNetscalerControlCenter
listNetscalerLoadBalancers
listNiciraNvpDevices
listOpenDaylightControllers
listOvsElements
listPaloAltoFirewalls
listSrxFirewalls
registerNetscalerControlCenter
```

### PR DESCRIPTION
**Pull request by utchoang**
Fixes #250 

* [x] Add support for all the network service providers which are not already supported
* [x] Each NSP must be implemented in its separate component
* [x] For each NSP component, add buttons and their forms in a modal and display a list of such NSP devices/resources in a table with pagination

### CODE REVIEW

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel 
I've tried to tested and enabled all NSP by running the zone wizard. However, it did not work with three NSPs F5, SRX and Palo Alto. The message returned for the call updateNetworkServiceProvider is "Provider is not ready, cannot Enable the provider, please configure the provider first". Could you please show me the way to configure these providers?

**Comment by rhtyd** [comment]
@utchoang that's expected if you don't have the plugin support and the providers are enabled in your environment via global settings or other external configuration, or if the management server is not a noredist build. Leave that as is, you may still work on to add support for them i.e. the add buttons/forms and list views.

**Comment by rhtyd** [comment]
@utchoang did you see my comment on https://github.com/apache/cloudstack-primate/issues/253 - can you pause your work on this meanwhile and instead work on https://github.com/apache/cloudstack-primate/issues/253 ? Thanks.

**Comment by rhtyd** [comment]
Hi @utchoang let me know if you've any questions on this feature. Thanks.

**Comment by utchoang** [comment]
image
Hi @rhtyd cc @svenvogel I've completed this task. Please review and help me test it as I can just test part of it locally.

**Comment by rhtyd** [comment]
Thanks @utchoang I've pinged you on another ticket - which is to add support for quota UI feature.

**Comment by svenvogel** [comment]
@rhtyd is this in a good state to merge?

**Comment by rhtyd** [comment]
Hi @svenvogel we're currently working towards tech preview, fixing/testing the last set of issues on the milestone. Once that is done, we'll move to 1.0 milestone issues and PRs. I'll ping you and @utchoang and keep everyone posted.

There's also a conflict, can you address @utchoang - thanks.

**Comment by rhtyd** [comment]
@utchoang - is this ready for review/merging? Sorry due to tech preview work I couldn't get back on this earlier. cc @svenvogel

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel  I completed resolved conflict. Please review it. Thanks

**Comment by rhtyd** [comment]
I'll review and merge this next
@utchoang can you fix the conflict? Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Thanks @utchoang let's try and get this merged in soon, can you address:
- Render the action button of left side of the tab widget/component
- Fix the translation key to use something like `$t("label." + key)`
- For the VR and VPC VR elements, show 'name' in the table and then state; for the name add a router-link so click would go to the specific VR resource view; use state column after name and display a `<status ...>` to show state icon (see ListView.vue for example)
Please do a round of testing and let me know; I'll do another round, review and merge this. Thanks again.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang looks better, but some issues; kindly address:
- On enable/disable of action buttons, for example enable/disable configdrive it throws error `i.parentPollActionCompletion is not a function`
- Fix labels (check for $t that don't have the label. prefix like `$t('label.`)
- If possible can you also add router-link for host and zone in the VR and VPC VR tabs? And for consistency show the fields/columns in this order - name, state, host, zone
- On deployment of a zone (see TestRYZonePR252 on primate-qa.cloudstack.cloud), all the NSP providers are enabled - you may test against legacy UI which does not enable all the providers (the prev set of providers/default enabled were fine)

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang still my comment on the zone deployment wizard hasn't been addressed; please address:
- The zone deployment wizard seems to now enable all the NSPs instead of just VirtualRouter, VPCVirtualRouter, Internallbvm
- Check why it says enabling security groups provider if SG is not enabled?

Rest LGTM, we can merge as soon as the zone deployment wizard regression is fixed. Thanks.

**Comment by utchoang** [comment]
@rhtyd Did you mean that when the zone deployment, all NSPs enabled are false? Because I understand that when the launch zone, it will enable all NSP. If I wrong, I'll undo the change this.

**Comment by rhtyd** [comment]
@utchoang please refer to old UI, we shouldn't enable all the providers but it usually is based on the isolation mode selected. For now only enable the NSPs I've mentioned, or better deploy a zone using legacy UI and this PR to see if for yourself. Thnx

**Comment by rhtyd** [comment]
Thanks @utchoang I'll review later today/tomorrow
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Good work @utchoang LGTM  will merge now!

**Pull request merged**
