### PR TITLE
view: fix actionbutton args method resource

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes undefined `action.resource`,
https://github.com/apache/cloudstack-primate/blob/master/src/views/AutogenView.vue#L562

### CODE REVIEW

**Comment by rhtyd** [comment]
Did not test lgtm

**Comment by DaanHoogland** [comment]
@rhtyd @shwstppr I can cherry pick this on bootsetup (#313 ) and test?

**Comment by DaanHoogland** [comment]
right, never mind, /me blind

**Comment by rhtyd** [comment]
@DaanHoogland just merge latest Primate master on your branch

**Pull request merged**
