### PR TITLE
Set deploy-as-is to default on VMware

### PR DESCRIPTION
**Pull request by nvazquez**
Do not set dpeloy-as-is as optional - use by default on VMware

### CODE REVIEW

**Comment by rhtyd** [comment]
@andrijapanicsb can you review/test this and against expected feature for upstream?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@nvazquez @rhtyd will this make Primate UI backward incompatible?

**Comment by rhtyd** [comment]
Yes @shwstppr. Other than checking for backend version there'll be no way to toggle the behaviour. I see many other backend/API changes that were implemented in 4.15 so largely Primate 1.0/GA will work with only 4.15 onwards, which we can speficy in the release notes - http://docs.cloudstack.apache.org/en/latest/installguide/primate.html#requirements

@nvazquez is this ready for merging?

**Comment by nvazquez** [comment]
Yes @rhtyd its good to go

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
