### PR TITLE
Use scaleVirtualMachine API instead of changeServiceForVirtualMachine

### PR DESCRIPTION
**Pull request by Pearl1594**
Align with Legacy UI and call scaleVirtualMachine API when attempting scaling

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by GabrielBrascher** [comment]
For reference, here follows some CloudStack issues raised due to changeServiceForVIrtualMachine API command problems:

- https://github.com/apache/cloudstack/issues/3110
- https://github.com/apache/cloudstack/issues/4125

**Comment by davidjumani** [comment]
Thanks @GabrielBrascher There were a few other reasons we went with changeServiceForVirtualMachine which I can't recall atm

**Comment by rhtyd** [comment]
@davidjumani @Pearl1594 @shwstppr can you share reasons for the change - thanks. I see legacy UI uses the scale API, is that it?

**Review by shwstppr — APPROVED** [review]
LGTM. Consistent with legacy UI. As per https://github.com/apache/cloudstack/issues/4125 changeServiceForVirtualMachine seems to be having issues and `scaleVirtualMachine` handles both running and stopped VMs.
@davidjumani if there is any corner case failing we can handle in backend

**Comment by Pearl1594** [comment]
@rhtyd 
1. changeServiceForVirtualMachine isn't used by the legacy UI either when we attempt scaling
2. scaleVirtualMachine does what changeServiceForVirtualMachine does - i.e., updates the service offering, and in addition to that, it also performs volume resizing.

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM.

CloudStack UI currently also does not use the `changeServiceForVIrtualMachine`. Additionally, there are a couple of open issues regarding `changeServiceForVIrtualMachine` API command problems:
- apache/cloudstack#3110
- apache/cloudstack#4125

**Pull request merged**
