### PR TITLE
Explore Test Automation

### PR DESCRIPTION
**Pull request by utchoang**
Open for #299
cc @svenvogel

### CODE REVIEW

**Comment by rhtyd** [comment]
@utchoang thanks, can you also check if Travis runs these test? Maybe add test/run command in the .travis.yml

**Comment by rhtyd** [comment]
If possible could you also explore a way to add some unit test for other components/widgets (an example for a small form, or tab component) and the autogenview component. Thanks.

**Comment by utchoang** [comment]
@rhtyd OK, got it I'm still in progress after completing https://github.com/apache/cloudstack-primate/pull/324 first.

**Comment by utchoang** [comment]
* components > Widget > Status
image

* components > Views > ActionButton
image

**Comment by rhtyd** [comment]
Good progress @utchoang

**Comment by utchoang** [comment]
* Views > AutogenView.vue - processing 31%
image

**Comment by rhtyd** [comment]
Good progress @utchoang keep it up!

**Comment by utchoang** [comment]
* Views > AutogenView.vue - processing 43%
image

**Comment by utchoang** [comment]
* Views > AutogenView.vue - processing 65%
image

**Comment by utchoang** [comment]
* Views > AutogenView.vue - processing 91%

image

**Comment by rhtyd** [comment]
Great work @utchoang I think some coverage (80+%) is a good start!

**Comment by rhtyd** [comment]
Let me know if you're going further or when this PR reaches a state to be merged? cc @svenvogel

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel OK, I got it. I think some further adjustments are needed to complete it.
I will notify after completion. Thanks.

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I've completed explore test automation. Please review and let me know your comments.

**Comment by rhtyd** [comment]
Tests should run slightly faster now, 3x faster in my env: (from over 90s)
```
 PASS  tests/unit/components/widgets/Status.spec.js
 PASS  tests/unit/components/view/ActionButton.spec.js
 PASS  tests/unit/views/AutogenView.spec.js (14.795s)

=============================== Coverage summary ===============================
Statements   : 5.22% ( 570/10914 )
Branches     : 6.91% ( 346/5005 )
Functions    : 2.36% ( 86/3639 )
Lines        : 5.22% ( 566/10849 )
================================================================================

Test Suites: 3 passed, 3 total
Tests:       104 passed, 104 total
Snapshots:   0 total
Time:        28.74s
Ran all test suites.
```

@utchoang can you make the following changes:
- in the `it()` and any `describe()` please use a full human-readable sentence to say what your test is doing (instead of short strings are `testCase...`)
- Can you add more one example unit test for a form or tab component in `src/views/` path, for example src/views/compute/MigrateWizard.vue (I picked smallest by file size)

Thanks for the effort, this looks good overall.

**Comment by utchoang** [comment]
* Views > compute > MigrateWizard.vue
image

**Comment by rhtyd** [comment]
Thanks @utchoang I'll review and merge over due course.

@DaanHoogland - you want to review this? Thanks.

**Comment by rhtyd** [comment]
@DaanHoogland any concerns on this PR?

**Comment by DaanHoogland** [comment]
code itself looks rather good @utchoang @rhtyd . It is not clear from the outside that this is meant to be extended. It is, is it? I'm would like to see some entry point that helps contributing, except for internal developer drive.
- Is there a Howto write your first component test?
- do we have conventions specific to the project?
- is there a link that will help understand the underlying test framework?
and as future policy to all that
- will we start requiring developers to extend/contribute?

**Comment by rhtyd** [comment]
@DaanHoogland The purpose currently is limited to introduce some unit testing early in the project and add few example test (esp. for core components to act as a quick smoketest that run with Travis for each PR).
- we've eslint to do several of the conventions related checks
- the way we write a component is pretty standard (we use a single-file-component, where within the component we've html, css and js code)
- the link is on the readme for the overall VueJS guide, https://vuejs.org/v2/guide/unit-testing.html (I'll add links and maybe a wiki page with some docs later)
- at the moment we don't want developers breaking some core components, so for starters this is largely to guard those components (esp the AutogenView); we'll identify and explore other critical components and  write tests for that but the project will still require some manual QA

@utchoang can you add a markdown file under `docs` say `docs/test.md` to document how to write a unit test for a component.

**Comment by DaanHoogland** [comment]
To be extra clear, I have no objections with this PR. code looks good as far as I can judge.

**Comment by rhtyd** [comment]
Closing/opening PR to rekick Travis

**Comment by rhtyd** [comment]
Still failing, let's revisit this later.

**Comment by utchoang** [comment]
@rhtyd I get the following error but I don't understand where the problem is? Do you have any ideas?
image

**Comment by utchoang** [comment]
@rhtyd Completed!

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Thanks @utchoang I'll merge this soon after the last few open PRs towards 1.0/GA milestone
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Manually tested build passes ok

**Pull request merged**
