### PR TITLE
Add missing internationlization to search and pagination

### PR DESCRIPTION
**Pull request by nvazquez**
Missing internationalization on the search bar and pagination "Showing X results" and pagination dropdown on various views

image
image

image
image

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani this as well, thnx

**Comment by davidjumani** [comment]
Tested a few pages. LGTM

**Pull request merged**
