### PR TITLE
Resource view style/layout improvement

### PR DESCRIPTION
**Pull request by RitchieVincent**

### CODE REVIEW

**Comment by rhtyd** [comment]
@RitchieVincent I reviewed and made some changes (see https://github.com/apache/cloudstack-primate/pull/100/commits/90a1e223e81fe45b741c2d0f9111fa5a56eb50e6), kindly review my changes around `a-progress`, and fix all the a-progress to show up to fill the width leave some place on left and right side. 

This is what it looks now:
Screenshot from 2020-01-10 12-28-38

**Comment by rhtyd** [comment]
@RitchieVincent ping - can you address styling issues?

**Comment by RitchieVincent** [comment]
> @RitchieVincent ping - can you address styling issues?

Should be all good to go now

**Comment by rhtyd** [comment]
@RitchieVincent the issues have not been addressed yet:

1. The width and label issue is not fixed for all a-progress, for example in zone/cluster:
Screenshot from 2020-01-15 12-23-17

2. The issue of buttons on the bottom of a nic description block in the instance hardware tab:
Screenshot from 2020-01-15 12-25-20

**Comment by RitchieVincent** [comment]
> @RitchieVincent the issues have not been addressed yet:
> 
> 1. The width and label issue is not fixed for all a-progress, for example in zone/cluster:
>    Screenshot from 2020-01-15 12-23-17
> 2. The issue of buttons on the bottom of a nic description block in the instance hardware tab:
>    Screenshot from 2020-01-15 12-25-20

The second issue (buttons) should already be fixed, I applied that fix yesterday in #a11f6f9. Could you let me know if you're still seeing the issue, and if so, where?
The progress bar issue is also fixed now, along with a couple of other minor tweaks.

**Pull request merged**
