### PR TITLE
Fix reload data after delete vm

### PR DESCRIPTION
**Pull request by utchoang**
@blueorangutan package

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
Fixes #753 
@rhtyd @davidjumani cc @svenvogel 
Please review it. Thanks.

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM! Thanks @utchoang

**Comment by rhtyd** [comment]
@davidjumani is this good to go, you've tested it? Or, will you explore a simpler fix?

**Comment by davidjumani** [comment]
@rhtyd I think this is fine, since not calling the pollJob would result in the progress notification not being displayed

**Comment by davidjumani** [comment]
I also think similar changes might be required. After an async job completes the page refreshes. However, it shouldn't if the user is not on the same page. Eg: After deleting a VM, the page should not refresh if the user is viewing a template

**Pull request merged**
