### PR TITLE
Add missing B&R features

### PR DESCRIPTION
**Pull request by utchoang**
Open for https://github.com/apache/cloudstack-primate/issues/253

* [x] Add offering support that imports external offering
* [x] Support for backup user-defined schedule
* [x] Restore volume and attach it to a VM from a backup

### CODE REVIEW

**Comment by utchoang** [comment]
* Support for backup user-defined schedule
image
image
image
image
image

**Comment by utchoang** [comment]
* Restore volume and attach it to a VM from a backup
image

**Comment by utchoang** [comment]
* Add offering support that imports external offering
image

**Comment by utchoang** [comment]
Hi @rhtyd cc @svenvogel 
I've completed. Please review and let me know your comments.

**Comment by rhtyd** [comment]
Hi @utchoang - is it ready for review? Thanks.

**Comment by utchoang** [comment]
Hi @rhtyd Yes. Please review it. Thanks.

**Comment by rhtyd** [comment]
Great I'll start review and merge @utchoang 

You may carry on with your https://github.com/apache/cloudstack-primate/pull/252 or feel free to pick any bugs - but do check existing PRs in case you end up duplicating the effort. Thanks.

**Pull request merged**
