### PR TITLE
view: fix runDiagnostic output display

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes: #293 

Screenshot from 2020-04-17 16-04-21

### CODE REVIEW

**Comment by rhtyd** [comment]
@shwstppr the output should also show stderr and exit value like old UI:
```
exitcode: 0

stderr:

stdout: PING 8.8.8.8 (8.8.8.8): 56 data bytes 64 bytes from 8.8.8.8: icmp_seq=0 ttl=50 time=7.575 ms 64 bytes from 8.8.8.8: icmp_seq=1 ttl=50 time=8.030 ms 64 bytes from 8.8.8.8: icmp_seq=2 ttl=50 time=14.950 ms 64 bytes from 8.8.8.8: icmp_seq=3 ttl=50 time=7.617 ms --- 8.8.8.8 ping statistics --- 4 packets transmitted, 4 packets received, 0% packet loss round-trip min/avg/max/stddev = 7.575/9.543/14.950/3.127 ms
```

Side-note I'm getting network error, for some reason the API request fails that I couldn't debug - are you seeing this as well (when using a non-local mgmt server env):
Screenshot from 2020-04-22 12-57-39

**Comment by shwstppr** [comment]
@rhtyd it works with a lab env and also with cloudmonkey local env
Made changes to show stderr and errorCode,
Screenshot from 2020-04-22 15-36-06

**Comment by rhtyd** [comment]
@shwstppr please follow the changes in future/related PRs

**Comment by shwstppr** [comment]
@rhtyd I'll ask before making changes in future/related PRs

**Pull request merged**
