### PR TITLE
FIX - Detail setting tab interface

### PR DESCRIPTION
**Pull request by utchoang**
@rhtyd cc @svenvogel 
- Before
image

- After:
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan package

**Review by davidjumani — CHANGES_REQUESTED** [review]
@utchoang Could you add an autofocus to the key ?

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM! Thanks @utchoang

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
