### PR TITLE
Displaying time as per user timezone

### PR DESCRIPTION
**Pull request by davidjumani**
Alters the time based on timezoneoffset passed during user login

Screenshot from 2020-12-18 15-02-26
Screenshot from 2020-12-18 15-02-15

Screenshot from 2020-12-18 15-02-39
Screenshot from 2020-12-18 15-02-45

Screenshot from 2020-12-18 15-03-02
Screenshot from 2020-12-18 15-02-55

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
