### PR TITLE
vApps frontend support

### PR DESCRIPTION
**Pull request by shwstppr**
Changes in backend

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@shwstppr @nvazquez is this ready for review/merging or are we expecting more changes?

**Comment by shwstppr** [comment]
changes for licenses remaining @rhtyd

**Comment by rhtyd** [comment]
@shwstppr @nvazquez is this ready for review/testing now?
@blueorangutan package

**Comment by shwstppr** [comment]
@rhtyd yes, please review

**Pull request merged**
