### PR TITLE
Cluster form

### PR DESCRIPTION
**Pull request by RitchieVincent**
@rhtyd As we discussed, the dedicate option has been left out for now. I think once the other dedicated domain PR (#113 ) has been merged in it might be a good idea to tweak it slightly so that I can import that functionality in to this form.

### CODE REVIEW

**Comment by RitchieVincent** [comment]
@rhtyd I've pulled the dedicated domain work in to this branch, and added the dedicated option.

**Comment by rhtyd** [comment]
@RitchieVincent can you merge latest master and fix the conflicts? I've merged the re-usable dedicated components.

**Comment by RitchieVincent** [comment]
@rhtyd Conflicts fixed.

**Comment by rhtyd** [comment]
@RitchieVincent can you check and fix the popover issues, use placeholder for api description instead?

**Pull request merged**
