### PR TITLE
view: list filtering

### LINKED ISSUE #213: [BUG] Missing Instance/VM 'Filter by' functionality
**Describe the bug**
It's impossible to filter by owned, running, stopped or destroyed instances, as in the old UI.

**To Reproduce**
1. Go to 'Compute > Instances' - the 'Filter by' functionality is missing.

**Expected behavior**
There should be a way to filter by owned, running, stopped or destroyed instances, as in the old UI.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
This filtering is missing also in the following pages:
- Templates

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #213

### CODE REVIEW

**Comment by shwstppr** [comment]
@rhtyd will something like this make sense?

**Comment by rhtyd** [comment]
@shwstppr see table/column filtering in antd, if that is not possible we can go with your approach

**Comment by shwstppr** [comment]
@rhtyd I've implemented table column filtering with antd here https://github.com/shapeblue/cloudstack-primate/tree/feature-list-filter-alt
Screenshot from 2020-05-04 12-14-03

Since default filtering UI shows checkboxes and API won't support multiple states for filtering, I'll have to implement custom UI

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Implemented that with a simpler fix, closing. Thanks.

**Pull request closed without merging**
