### PR TITLE
Adding option to copy resource name and IP

### PR DESCRIPTION
**Pull request by davidjumani**
- Adding option to copy resource name on avatar click
- Fixing alignment of console icon
### Before :
Screenshot from 2020-10-13 18-10-48

### After :
Screenshot from 2020-10-15 10-42-32

### Copy notifications :
Screenshot from 2020-10-15 12-52-56
Screenshot from 2020-10-15 12-52-34

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Could be confusing for users - if they're clicking say on an OS logo avatar; instead you can be explicit by adding a tiny copy button to two things - names and IPs both in list and resource view (good to have, not urgent for 1.0). Or at least we can be explicit to say what was copied to clipboard like `copied to clipboard: string-here`

**Comment by davidjumani** [comment]
@rhtyd Added the copied string to the notification. Also added option to copy the ip address

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Pull request merged**
