### PR TITLE
Refresh data every 30 seconds

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes https://github.com/apache/cloudstack-primate/issues/630

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
This is not ideal or fail-safe, what-if it takes more than n * 30s for the batched jobs to finished (where n is the number of resources on which a group action was performed)?

**Comment by davidjumani** [comment]
@rhtyd It refreshes the page every 30 seconds irrespective of a batch job to ensure the user always has the latest details available. It also fixes the batch job refresh since the jobs should complete at some time, and within 30 seconds of them completing, the page refreshes

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani if we've https://github.com/apache/cloudstack-primate/pull/665 can we close this?

**Comment by davidjumani** [comment]
@rhtyd I prefer having this rather than #665 since that is for a specific case (We can use parts of that such as the event when an async job has been completed to do additional stuff that might be needed in the future). This one will ensure the user has the most up to date info at all times. Can extend the refresh interval to 60sec if 30 seems too short

**Comment by rhtyd** [comment]
Can you advise a case where doing infinite refresh makes sense, and where the async event based refresh in the other PR doesn't fix refresh issue?

**Comment by davidjumani** [comment]
It makes sense where multiple users are logged in and make changes, so that the current user gets the most up to date info. Can close this if it is a niche case!

**Comment by rhtyd** [comment]
Closing on your remark David

**Pull request closed without merging**
