### PR TITLE
FIX - compute - Create snapshot from virtual machine with managed storage

### LINKED ISSUE #807: [IIMPROVEMENT] create snapshot from virtual machine with managed storage
Hi @rhtyd @utchoang 

Storage Snapshot functionality.

in the old ui we have here a storage snapshot functionality. 
image

we should add them in the new ui too like the old ui for the user of managed storage
image

@utchoang can you create a PR please?

Cheers

Sven

### PR DESCRIPTION
**Pull request by utchoang**
Fixes #807

### CODE REVIEW

**Comment by utchoang** [comment]
image
image

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@rhtyd @svenvogel Please review it. Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by svenvogel — APPROVED** [review]

**Comment by davidjumani** [comment]
@utchoang There also needs to be a check for `quiescevm` on the volume
https://github.com/apache/cloudstack/blob/master/ui/scripts/instances.js#L1255

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by svenvogel** [comment]
@rhtyd @davidjumani is this ready to go? 😄

**Comment by svenvogel** [comment]
> @utchoang There also needs to be a check for `quiescevm` on the volume
> https://github.com/apache/cloudstack/blob/master/ui/scripts/instances.js#L1255

wo what i see is that there is no squeezing in managed storage. we dont need at the moment an quiesed button.

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@davidjumani Please review again. Thank you.

**Comment by svenvogel** [comment]
@davidjumani @utchoang maybe I am wrong but there is NO qiescevm on a managed storage volume. I don’t know if there is something in VMware but I think the mechanism is another one. Please refer #3724 in cloudstack. 
https://github.com/apache/cloudstack/pull/3724#issue-346702676
If this so we can remove the quiescing and it’s at the Moment for volume snapshots not important. 
@rhtyd can you clarify?

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM. However, this needs to be tested on VMware

**Comment by svenvogel** [comment]
@davidjumani can you clarify where you use "quiescevm" in VMware and which feature you want to test? there are normal VM Snapshots and i only know volume snapshot like VVOLs. Do you speak about VVOLs? Can you link or clarify the test?

**Comment by davidjumani** [comment]
@svenvogel Not too sure about it but I do see it as a parameter in volume snapshot as well as while creating VMware snapshots

**Comment by svenvogel** [comment]
@davidjumani how can we proceed? i see there is a parameter but which time it is used? 
if there is no test scenario then why are we testing it? normally functionality is not changed to old UI.

take a look here. its included in the old UI.
image
image

@rhtyd @utchoang @davidjumani is the master frozen? i think this is ready to merge.

**Comment by utchoang** [comment]
@davidjumani @rhtyd Do you test OK and ready to merge?

**Comment by GabrielBrascher** [comment]
Well, from what I understand, what it matters here is not the hypervisor (VMware). But the volume itself with quiescevm enabled. One can test it by mocking such situation.

Also, the API returns such information on the list volumes call which enabled to implement the UI on same approach as the old UI. I don't see any problem here.

**Comment by davidjumani** [comment]
I too don't see any blocker here but would like the snapshot API call tested on a volume with quiescevm enabled (mocked also works fine)

**Comment by svenvogel** [comment]
@davidjumani @GabrielBrascher can we merge?

**Comment by utchoang** [comment]
@rhtyd @davidjumani cc @svenvogel Is it possible to merge this PR?

**Comment by davidjumani** [comment]
I'm okay with having this merged

**Review by GabrielBrascher — APPROVED** [review]
Thanks for the PR @utchoang! LGTM

**Pull request merged**
