### PR TITLE
Add host form

### PR DESCRIPTION
**Pull request by RitchieVincent**
@rhtyd I believe I've done what I can here, but I can't figure out how to submit the form on the existing UI, so if you can figure that out and let me know, then I can finish this PR up. At the moment it's submitting all the same data to the API, and getting the same error as the current UI.

### CODE REVIEW

**Comment by rhtyd** [comment]
@RitchieVincent can you merge latest master and fix the conflicts? I've merged the re-usable dedicated components.

**Comment by RitchieVincent** [comment]
@rhtyd Conflicts fixed.

**Comment by rhtyd** [comment]
@RitchieVincent can you check and fix the popover issues, use placeholder for api description instead?

**Comment by rhtyd** [comment]
TODO: test/validate against vmware, then merge

**Pull request merged**
