### PR TITLE
infra: vr healthcheck

### LINKED ISSUE #362: [FEATURE] VR health checks feature
Missing feature in Primate, VR health check feature in router list view and resource view.

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #362 
Screenshot from 2020-06-17 14-10-34

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@shwstppr can you merge the conflict and use  the new nics component from master instead?

**Comment by shwstppr** [comment]
@rhtyd Done. Old nics view was much better,
Screenshot from 2020-06-22 10-31-45
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Basic tests performed, LGTM.

**Pull request merged**
