### PR TITLE
Account Certs Tab

### PR DESCRIPTION
**Pull request by utchoang**
@rhtyd @svenvogel 
This is the design of the account certificate tab. Please let me know your comments.
1. List SSL Certificate (listSslCerts)
cert_1

2. Add Certificate (uploadSslCert)
cert_3

3. Quickview
cert_2

4. Delete certificate (deleteSslCert)
cert_4

### CODE REVIEW

**Comment by rhtyd** [comment]
Can you rebase this against latest master?

**Comment by utchoang** [comment]
> Kindly check against latest master, your PR reverts recent changes, also add license header in new file.

**Comment by rhtyd** [comment]
Screenshot look good, I'll review test and merge later today. Thanks @utchoang @svenvogel

**Comment by utchoang** [comment]
I'll rebase the master and create a new PR

**Pull request closed without merging**
