### PR TITLE
Adding custom change affinity view

### LINKED ISSUE #386: [BUG] Change Affinity for VM form missing
Change affinity for a VM missing, old UI form looks like this: (notice multi-select)
Screenshot from 2020-06-08 08-33-52

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #386 

Screenshot from 2020-06-16 16-12-13

Pagination supported but hidden if less than 10 by default

### CODE REVIEW

**Comment by rhtyd** [comment]
@davidjumani can you check old UI, we probably want pagination and search support (the list API could in fact return a lot of rules in very large env; if the count is say less than 10 then we can hide the pagination component).

**Comment by davidjumani** [comment]
@rhtyd  Is there a need to add this vpc tier selection? It does not affect listing / updating the affinity group in any way. It only shows up while listing the vm through the configure network vpc
Screenshot from 2020-06-16 15-30-46
Screenshot from 2020-06-16 15-39-42

**Comment by rhtyd** [comment]
The vpc tier is not needed (bug in legacy UI)

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@shwstppr Could you get the search bar to be on the right?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
MIssing:
- Page size selection
- Width css rules (nit)

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
Count is broken for the listAffinityGroups API so the pagination gets messed up

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd Would it make sense to show the description too? Not there in the legacy UI

**Comment by rhtyd** [comment]
Sure.

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Test LGTM

**Pull request merged**
