### PR TITLE
Hiding vm self filter when in project view

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes https://github.com/apache/cloudstack-primate/issues/696

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
Um.. not sure why we hide the filter?
If you are OK with it, feel free to merge and close the original issue please.

**Comment by andrijapanicsb** [comment]
LGTM, merging.

**Pull request merged**
