### PR TITLE
Contextual info for Service offering forms and upload custom ssl certs

### PR DESCRIPTION
**Pull request by Pearl1594**
Contextual info for Service offering forms and upload custom ssl certs

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@Pearl1594 is this ready for review/merging?

**Comment by Pearl1594** [comment]
Yes @rhtyd

**Comment by rhtyd** [comment]
LGTM, @Pearl1594 if you do work on such PRs, prioritise forms/components that are User, DomainAdmin facing than only Admin facing.

**Pull request merged**
