### PR TITLE
offerings: add custom action

### PR DESCRIPTION
**Pull request by shwstppr**
TODO:
- [x] Compute Offering
- [x] System offering
- [x] Disk offering
- [x] Network offering
- [x] VPC offering

Add compute offering
Screenshot from 2020-02-18 11-15-50
Add system offering
Screenshot from 2020-02-18 11-24-55
Add disk offering
Screenshot from 2020-02-18 11-16-37
Add network offering
Screenshot from 2020-02-18 11-16-19
Add vpc offering
Screenshot from 2020-02-18 11-23-06

### CODE REVIEW

**Comment by rhtyd** [comment]
@shwstppr general notes: 
- Avoid using `this.$t()` withing `<template>...`, just use `$t(...)`
- For translation, simply use the API arg such as `zoneid`, instead of `label.zoneid` (we'll fix this to make translation keys consistent)

**Comment by shwstppr** [comment]
@rhtyd this is ready for review/test

**Comment by rhtyd** [comment]
@shwstppr can you review this, address all the label/issues; we want to prefer using the API arg as the translatable string. Ping me when this is ready for review, thanks.

**Comment by shwstppr** [comment]
@rhtyd fixed label. string usage.
What happens in cases when some input field does not directly correspond to API parameter. Such as we have a `QOS Type` field for creating compute offerings but it just to manipulate API parameters, `bytesreadrate`, `byteswriterate`, etc

**Comment by rhtyd** [comment]
@shwstppr please address:

Compute/service offering:
- Write-cache type missing
- message notification translation incomplete (check/add in locales/en.json)

Disk offering:
- Check my changes, cache modes were wrong
- message notification translation incomplete (check/add in locales/en.json)

VPC offering:
- Support service and provider not on same line
- have the default values selected?
- message notification translation incomplete (check/add in locales/en.json)

Network offering:
- Several label translation fixes
- message notification translation incomplete (check/add in locales/en.json)
- Does not work, needs testing/fixing for isolated, shared, l2 types

**Comment by shwstppr** [comment]
Addressed above issues @rhtyd. Ready for re-test

**Pull request merged**
