### PR TITLE
Fix users form, network SG and VPC

### PR DESCRIPTION
**Pull request by utchoang**
@davidjumani @rhtyd cc @svenvogel 
- [x] Hide SG feature when there are no zones with SG enabled (may be done during API discovery, don't create the SG route if no zones have SG enabled)
- [x] Fix the add and edit users form to show timezone as a list of the searchable dropdown like in the add account form

- [x] Change or remove (explain?) what "Add new VM" is from VPC tiers tab; (a) allow users to add existing VMs or (b) deploy new VMs on the specific VPC tier, the deployment form does not auto-select the specific VPC tier [preferably the former, to add existing vms]

### CODE REVIEW

**Comment by utchoang** [comment]
* Add user:
ảnh
ảnh

* Edit user:
ảnh

**Comment by utchoang** [comment]
* Add instance from VPC tab
image

**Comment by utchoang** [comment]
@davidjumani I've completed this task. Please review. Thanks.

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
Thanks @utchoang Will review soon!

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you fix the conflicts against latest master?

**Pull request merged**
