### PR TITLE
Destroying messages after logout

### LINKED ISSUE #816: [BUG] Async job notification remains on logout
**Describe the bug**
Async job notification remains on logout

Screenshot from 2020-10-22 17-54-17

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #816

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
Not destroying the notifications since that'll clear the session expired notification

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
