### PR TITLE
Fix unmanage / manager cluster

### LINKED ISSUE #396: [BUG] Check fix unmanage cluster action when cluster is ExternalManaged
Check against legacy UI if unmanage cluster action buttons should be shown when cluster is ExternalManaged

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #396

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd ready to go!

**Comment by rhtyd** [comment]
@davidjumani it gets a bit complicated as the state itself is determined as follows, legacy code reference:
```
        if (jsonObj.managedstate == "Managed") {
            jsonObj.state = jsonObj.allocationstate; //jsonObj.state == Enabled, Disabled
        } else {
            jsonObj.state = jsonObj.managedstate; //jsonObj.state == Unmanaged, PrepareUnmanaged, PrepareUnmanagedError
        }
  
```

**Comment by rhtyd** [comment]
The check can be based on record.managedstate and record.allocationstate to show/hide the buttons

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd Good catch! Changes made!

**Comment by rhtyd** [comment]
@davidjumani see we could further simply it as the allocation state will able be either Enabled or Disabled (see Cluster.java/enums)

**Pull request merged**
