### PR TITLE
Fixing permission issues

### LINKED ISSUE #463: [BUG] User: Permission related issues
Compute:
- SSH keys: create SSH key without specifying public key creates private key, could we make it easier for user to copy or download it? Or, simply cause a file to be downloaded after the form finishes.

Network:
- VPN users: add user causes failure (could be backend issue, or this needs to be allowed only after VPN is enabled on some network?)
- After adding VPC tier it does not refresh the network/tiers list

Templates:
- Edit Template and edit Template permission action show to user (restrict to owner or domain/admin?)
- Copy and Delete Template show irrespective of user/account/acl checks
- Setting tab show for edit/add settings to templates to non-owner/user (read-only is fine)
- Download template buttons show without doing checks (only Domain Admin and regular users can modify only their own Public templates)
- Users are unable to edit their template - Don't show isrouting parameter is create/edit template for users

ISOs:
- Edit ISO and edit ISO permission action show to user (restrict to owner or domain/admin?)
- Copy and Delete ISO show irrespective of user/account/acl checks
- Download ISO button show without doing checks (only Domain Admin and regular users can modify only their own Public templates)

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #463 

Compute:

- [x] SSH keys: create SSH key without specifying public key creates private key, could we make it easier for user to copy or download it? Or, simply cause a file to be downloaded after the form finishes. : Shows a dialog to copy or download key

Network:

~- [ ] VPN users: add user causes failure : Looks like a backend issue. VPN is enabled on networks within the zone but still fails to add the user~
- [x] After adding VPC tier it does not refresh the network/tiers list

Templates:

- [x] Edit Template and edit Template permission action show to user (restrict to owner or domain/admin?)
- [x] Copy and Delete Template show irrespective of user/account/acl checks
- [x] Setting tab show for edit/add settings to templates to non-owner/user (read-only is fine)
- [x] Download template buttons show without doing checks (only Domain Admin and regular users can modify only their own Public templates)
- [x] Users are unable to edit their template - Don't show isrouting parameter is create/edit template for users

ISOs:

- [x] Edit ISO and edit ISO permission action show to user (restrict to owner or domain/admin?)
- [x] Copy and Delete ISO show irrespective of user/account/acl checks
- [x] Download ISO button show without doing checks (only Domain Admin and regular users can modify only their own Public templates)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd Good to go!

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Please merge latest master and fix any conflicts? Thanks.

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@Pearl1594 are you testing as well, if so I'll merge if you're LGTM

**Comment by Pearl1594** [comment]
@blueorangutan package

**Pull request merged**
