### PR TITLE
Add container build files and instructions

### PR DESCRIPTION
**Pull request by onitake**
(as discussed in #12 )

This PR adds:
* a Dockerfile
* a build script that injects some labels from git
* an example nginx config for running the built webpack
* instructions on how to run the container

### CODE REVIEW

**Comment by rhtyd** [comment]
I'll test again, @onitake I get the following:
Step 4/11 : COPY . /build/
 ---> f33ff9fa996b
Step 5/11 : RUN	npm install
 ---> Running in 09645d40dd4c
audited 930064 packages in 12.06s
found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 09645d40dd4c
 ---> e3f63e3d1cc7
Step 6/11 : RUN npm run build
 ---> Running in eeeb5d7a833e

> primate@0.1.0 build /build
> vue-cli-service build

Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! primate@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the primate@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-20T10_13_05_191Z-debug.log

**Comment by rhtyd** [comment]
Sorry just read, we'll need to merge #12 first it seems

**Comment by rhtyd** [comment]
I'll go ahead and merge this @onitake - if there are any issues post merge, kindly test and send another PR. I'll test later this week.

**Comment by onitake** [comment]
A segfault?!?!?
That sounds pretty serious... But I never ran into anything of that sort myself.
Are you sure it's not a Docker or memory exhaustion issue?

**Pull request merged**
