### PR TITLE
FIX - Add cluster - password is not masked

### PR DESCRIPTION
**Pull request by utchoang**
Open for https://github.com/apache/cloudstack-primate/issues/612
@rhtyd cc @svenvogel I've completed fixed. Please review it. Thanks.
image

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by Pearl1594 — COMMENTED** [review]
LGTM
@utchoang We may want to also change the api call for addCluster to POST to hide the password in the request parameter. Thanks

**Comment by utchoang** [comment]
@blueorangutan package

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Review by davidjumani — APPROVED** [review]
LGTM. Thanks @utchoang @Pearl1594 
@rhtyd Good to go!

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
