### PR TITLE
Fixes reload of page on session expiry

### LINKED ISSUE #650: [BUG] After session expire the page reloads once more
**Describe the bug**
When a session has expired, and the user refreshes the page, he's being displayed with the login screen. Right after that the page refreshes once more. 

**To Reproduce**

1. Leave a session to expire
2. Refresh the page
3. once loaded observe the page will refresh once more

**Expected behavior**
One refresh should be enough 

**Screenshots**
reload

### PR DESCRIPTION
**Pull request by Pearl1594**
Fixes #650

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Did a quick test LGTM (I deleted the jsession cookie and click a router-link), need more testing for cases (a) on mgmt server restart, (b) on actual session expiry (say after 30mins...) cc @davidjumani

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@Pearl1594 cc @davidjumani - is this ready for review/testing?

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani can you review as well?

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani are you LGTM on this?

**Comment by davidjumani** [comment]
Page still reloads after being pushed out, but without a significant delay. @borisstoyanov Could you test this fix ?

**Comment by rhtyd** [comment]
ping @borisstoyanov cc @andrijapanicsb can you review/test this, thanks

**Comment by andrijapanicsb** [comment]
Looks good to me:

-reduced session timeout to 1min, restarted mgmt

1. login, wait for 2minutes, go back to the same page, click on something, I get error that session has expired, redirected to the login screen - once I enter the login credentials - no more redirects/need to login again

2. login, wait for 2 minutes, do NOT click on anything, just refresh the page, I get the error that the session has expired, login once and then again all good (no more redirects / need to login again)

LGTM

**Pull request merged**
