### PR TITLE
Disallowing udp as a lb protocol

### PR DESCRIPTION
**Pull request by davidjumani**
UI fix for https://github.com/apache/cloudstack/pull/4501

lb

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
To be merged only if backend PR is merged. Can you review/advise @weizhouapache @ravening ?

**Comment by ravening** [comment]
> To be merged only if backend PR is merged. Can you review/advise @weizhouapache @ravening ?

@davidjumani @rhtyd it does support udp

```
(local) 🐱 > create loadbalancerrule name=test privateport=80 publicport=8080 protocol=udp account=admin domainid=04dfd1c6-c28e-11ea-9a43-0617bc003377 networkid=d396de4e-0e23-4e3b-a19a-1fe1ac35227c publicipid=6275b645-fac5-4b03-a2f1-40848655ffd0 algorithm=roundrobin
{
  "loadbalancer": {
    "account": "admin",
    "algorithm": "roundrobin",
    "cidrlist": "",
    "domain": "ROOT",
    "domainid": "04dfd1c6-c28e-11ea-9a43-0617bc003377",
    "fordisplay": true,
    "id": "d1883751-9e55-4104-a522-c6c5c09a123b",
    "name": "test",
    "networkid": "d396de4e-0e23-4e3b-a19a-1fe1ac35227c",
    "privateport": "80",
    "protocol": "udp",
    "publicip": "10.10.20.1",
    "publicipid": "6275b645-fac5-4b03-a2f1-40848655ffd0",
    "publicport": "8080",
    "state": "Add",
    "tags": [],
    "zoneid": "8ae93aed-7db1-4a1a-9030-db0efac6ba62",
    "zonename": "mgt122-10"
  }
}
```

**Comment by DaanHoogland** [comment]
@ravening , when you say "it does support udp" do you mean that actual udp based load-balancing takes place, and not just the api accepts the value for the protocol parameter?
Is this on the VR based loadbalancer (i.e. a process like ha-proxy running on the VR) or only on an external provider?

**Comment by ravening** [comment]
> @ravening , when you say "it does support udp" do you mean that actual udp based load-balancing takes place, and not just the api accepts the value for the protocol parameter?
> Is this on the VR based loadbalancer (i.e. a process like ha-proxy running on the VR) or only on an external provider?

@DaanHoogland ignore my previous comment. Found out that haproxy doesnt suport udp. so we can remove that option from cloudstack.


@davidjumani I already have a PR for haproxy based loadbalancer for ui in https://github.com/apache/cloudstack-primate/pull/778
If you are ok then I can make changes there only

**Comment by davidjumani** [comment]
Closing this as other load balancers might support udp

**Pull request closed without merging**
