### PR TITLE
Compute > Instances - Missing extended search functionality

### PR DESCRIPTION
**Pull request by utchoang**
@rhtyd cc @svenvogel 
Fixes https://github.com/apache/cloudstack-primate/issues/214

### CODE REVIEW

**Comment by utchoang** [comment]
* Instances:
image

**Comment by utchoang** [comment]
* Storage > Volumes:
image

**Comment by utchoang** [comment]
* Storage > VM Snapshots
image

**Comment by utchoang** [comment]
* Network > Guest networks
image

* Network > VPC
image

* Network > VPN Customer Gateway
image

* Templates
image

* Templates - ISO
image

* Events
image

* Projects
image

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel 
I've completed fixes. Please review and let me know your comments.

**Comment by rhtyd** [comment]
Thanks @utchoang I'll try to review and merge it this week

**Comment by shwstppr** [comment]
@rhtyd this can be reviewed

**Comment by rhtyd** [comment]
@utchoang can you fix the conflict? Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you help fix the merge conflicts? Thanks.

**Comment by rhtyd** [comment]
@utchoang can you fix the conflict, thanks

**Comment by utchoang** [comment]
@rhtyd I've resolved it. Thanks.

**Comment by rhtyd** [comment]
Can you review this @davidjumani

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@utchoang Domain / account level searches need to be hidden as per the user account level (Admin / user)

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
Tested. LGTM. However, would it make sense to change the colour of the filter icon or the placeholder in the search tab to show that there is a filter in effect ?

**Comment by rhtyd** [comment]
@utchoang can we show the filter button of left side of the searchbar? 
@blueorangutan package

**Comment by rhtyd** [comment]
Thanks @utchoang I'll kick tests
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you change the following:
- Rename clear to reset, click that should reset search and run search without any options selected
- search by account for VM (see legacy UI for reference)
- When filter is clicked disable (see `:disabled` I think) the searchbar (so user is not confused to type keywords/name on the searchbar and then click search); and when the focus goes away hide the filter form and enable search input again
- Add adv search for routers view to search by name, account, zone/pod/cluster

**Comment by utchoang** [comment]
@rhtyd I am not sure a few points:
* `Rename clear to reset, click that should reset search and run search without any options selected` means that when clicking the reset button it clears all filter options and search bar and run fetch data again.

* `Add adv search for routers view to search by name, account, zone/pod/cluster` I don't understand this. Please describe more clearly?
Thanks.

**Comment by rhtyd** [comment]
@utchoang
- yes, my thought is when a use clicks on the reset/clear we're effectively resetting the search
- Two things: (a) add account as a input in the search box, compare against old UI's adv search; (b) check old UI and goto some of the other list views such as go to Infra -> Routers -> you'll see some kind of adv search. So I think we should allow router search by name, account, zone, pod, cluster.

Screenshot from 2020-06-25 10-52-30

**Comment by utchoang** [comment]
@rhtyd I've added an advanced filter search for routers (below image). Thanks.
image

**Comment by rhtyd** [comment]
Thanks @utchoang I'll review
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you fix the conflicts? Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM tested as root admin, normal user

**Pull request merged**
