### PR TITLE
template/iso actions in zones tab and template/iso filter in list view

### LINKED ISSUE #278: [BUG] ISO - Update permissions form does not autodiscover operation, accounts and projects
**Describe the bug**
Update permissions form does not autodiscover operation, accounts and projects

**To Reproduce**
1. Go to ISOs
2. Select an iso
3. Click on Update permissioins
4. See that fields are not autodiscovering operation/account/project

**Expected behavior**
There should be dropdown option for the fields 

**Screenshots**
Screenshot 2020-04-02 at 16 38 52

### LINKED ISSUE #279: [BUG] Copy ISO Form does not discover values in fields. Also they seem to be displayed as API attributes
**Describe the bug**
Fields are not populated when selecting copy iso

**To Reproduce**
1. Go to ISOs
2. Select an iso
3. Click on Copy ISO
4. See that fields are not autodiscovering Source and destination and fields are displayed and api call attributes names 

Screenshot 2020-04-02 at 16 50 53

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #279

Screenshot from 2020-05-04 14-46-52
Screenshot from 2020-05-04 14-47-18
Screenshot from 2020-05-04 14-51-04
Screenshot from 2020-05-04 14-47-40

### CODE REVIEW

**Comment by rhtyd** [comment]
@shwstppr instead can you remove the copy icon and move it to the template/iso zones component where we have the delete button already?

**Comment by rhtyd** [comment]
@shwstppr instead can you remove the copy icon and move it to the template/iso zones component where we have the delete button already?

**Comment by shwstppr** [comment]
@rhtyd not sure about template/iso zones component. I see UI as below,
Screenshot from 2020-04-17 10-30-50

We are just showing a tab for template zones and there is no additional delete button there. Can you please point me to the relevant code.

**Comment by rhtyd** [comment]
@shwstppr move the copy and delete buttons/action to the iso and template zones components.

**Comment by shwstppr** [comment]
@rhtyd movde template/ISO actions in zone item list

**Comment by rhtyd** [comment]
@shwstppr can you merge latest master on this branch and resolve conflict?

**Comment by shwstppr** [comment]
@rhtyd merged latest master

**Comment by rhtyd** [comment]
Test issues:
- Don't poll for async job (both copy and delete operations), notification too early
- should refresh after async job poll, for delete if there are no zones, run router.go(-1)

I've added support for template/iso filtering.

**Comment by rhtyd** [comment]
remark @shwstppr - this was an untested PR, actions didn't work or show errors/success without doing proper polling.

**Comment by rhtyd** [comment]
Reviewed and fixed. Tested:
- Iso and template registration, fixes in form component
- Filter by for template/iso
- Copy and delete command for template/iso with job polling
- Go to preview page on deletion of template/iso with a single zone

**Pull request merged**
