### PR TITLE
Using post for uploadSslCert api 

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes https://github.com/apache/cloudstack-primate/issues/837

Ignore the api response error, passing dummy data
Screenshot from 2020-10-28 17-21-00

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
This may require a bit of testing as this changes the core AutogenView

**Comment by rhtyd** [comment]
Moving this to 1.1, not generally used or that important; get request seems to work OK.

**Comment by ravening** [comment]
tested fine

**Review by rhtyd — APPROVED** [review]

**Pull request merged**
