### PR TITLE
actions: route back on vm unmanage

### LINKED ISSUE #782: [BUG] Unmanage VM leads to a 404 page
**Describe the bug**
When you unmanage a VM, a 404 error (not found) page is shown.

**To Reproduce**

1. Log in as a User or an Admin
2. Go to 'Compute > Instances'
3. Click on an instance and then on the button 'Unmanage VM'

After the operation, the page is reloaded but the VM is no longer available which leads to 404 error page.

**Expected behavior**
Probably the user must be redirected back to the list of instances.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
None.

### PR DESCRIPTION
**Pull request by shwstppr**
Route back on VM unmanage

Fixes #782

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorganutan package

**Comment by davidjumani** [comment]
@blueorganutan package

**Review by davidjumani — APPROVED** [review]
Code LGTM. Needs testing

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM Thanks @shwstppr

**Pull request merged**
