### PR TITLE
Build and packaging improvements

### PR DESCRIPTION
**Pull request by utchoang**
Open for https://github.com/apache/cloudstack-primate/issues/510

### CODE REVIEW

**Comment by utchoang** [comment]
js/chunk-vendors.js reduced by 0.51 MiB
image
image

**Comment by utchoang** [comment]
js/chunk-vendors.js reduced by 0.28 MiB
image
image

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang is this ready for testing/merging?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I can only optimize the bundle for a small part. The rest have not found a better solution. You can review/test what is I've updated. Thanks

**Comment by rhtyd** [comment]
Thanks @utchoang since this changes library/dependencies, let's revisit the optimisation after 1.0/GA release. cc @svenvogel - what do you think?

**Comment by utchoang** [comment]
js/app.js reduced by >3.00 MiB
image
image

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you fix the conflict and retest the pkg building?

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Pl hold merging until we've some manual test confirmation

**Pull request merged**
