### PR TITLE
Confirmation by pressing Space on confirm screens

### LINKED ISSUE #781: [BUG] Confirmation by pressing Space on confirm screens
**Describe the bug**
Some usability from old ui can be implemented here as well. When ever we have a confirmation screen we need to click with the mouse, instead as per the old ui we can press Space to toggle the confirmation of expunge etc.. 

**To Reproduce**
Expunge a volume
Delete a VM 
and more...

**Screenshots**
Screenshot 2020-10-01 at 11 17 06

### PR DESCRIPTION
**Pull request by utchoang**
Fixes #781 
@rhtyd cc @svenvogel

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Good to have, could this cause any regressions?

**Comment by utchoang** [comment]
@rhtyd I think it won't cause a regression. Thanks.

**Comment by davidjumani** [comment]
@utchoang I think what @borisstoyanov meant was that hitting space toggles the value of the first button / checkbox / switch. An autofocus on the first form item would be an appropriate fix

**Comment by utchoang** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM. Need to check whether changes might be needed in other custom forms
Thanks @utchoang

**Pull request merged**
