### PR TITLE
Fix typo in display message

### LINKED ISSUE #865: [BUG] type : CVS vs CSV
**Describe the bug**
When creating a role, the input asked for is supposed to be CSV (not CVS)

image

**To Reproduce**

1. Log in as a User or an Admin
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android with device/screen details if applicable]

**Additional context**

### PR DESCRIPTION
**Pull request by ravening**
Fixes #865 

Small typo

Screenshot 2020-11-19 at 15 12 20

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
looks good @ravening tnx, hadn't bothered to find it yet ;)

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Review by utchoang — APPROVED** [review]
LGTM!

**Review by davidjumani — APPROVED** [review]
LGTM

**Pull request merged**
