### PR TITLE
FIX - Networks: Control show/hide PF & LB rules tabs

### LINKED ISSUE #678: [BUG] With VPC - LoadBalancing tab should be hidden if the IP is already used for i.e. Port Forwarding or Static NAT
In VPC, there is no preserve mode with Public IPs - and for Port Forwarding, StaticNAT and LoadBalancing - if any of these services is enabled on a single (additional) Public IP - the other 2 services/tabs/buttons should be hidden - otherwise, user will attempt to configure and get an error like below (an expected error):

image

### PR DESCRIPTION
**Pull request by utchoang**
Fixes #678 
@rhtyd cc @svenvogel

### CODE REVIEW

**Comment by utchoang** [comment]
- Case 1:
image

- Case 2:
image

- Case 3: 
image

- Case 4:
image

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
Control the` enable static NAT` button
- PF or LB rules:
image

- no tier, PF or LB rules:
image

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you test and advise when this is ready for testing? I navigated to the IP view from VPC -> select Admin-RR -> select IP address tab and select an IP and I see this:


Screenshot from 2020-09-24 13-22-06

**Comment by utchoang** [comment]
@rhtyd Sorry, I commit missing. Please try again. Thanks.

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
cc @DaanHoogland

**Comment by DaanHoogland** [comment]
@utchoang both portforwarding and loadbalancing disable the other two options, but the enable static nat button seems to be non-func:
image

**Comment by DaanHoogland** [comment]
after enabling static nat in the old UI:
image

**Comment by DaanHoogland** [comment]
disable static nat doesn't work either. marking this as blocker

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
great @utchoang all three work now

**Pull request merged**
