### PR TITLE
[FIX] New Instance dialog

### PR DESCRIPTION
**Pull request by utchoang**
Open for https://github.com/apache/cloudstack-primate/issues/263 and https://github.com/apache/cloudstack-primate/issues/375#issuecomment-638672427
* [x] Add scroller in the 'New instance' info
* [x] Can't "un-choose" the Zone/Pod/Host for the VM deployment

### CODE REVIEW

**Comment by utchoang** [comment]
* Add scroller in VM info
image
* Add "Default" option into the select box the Zone/Pod/Host for the VM deployment
image

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I've completed. Please review and testing. Thanks.

**Comment by rhtyd** [comment]
@utchoang I missed seeing this PR and pushed a fix, can you review my commit and close this PR if my commit fixes the issue:
https://github.com/apache/cloudstack-primate/commit/0468b826a3fa35970010cc3736043fdce1d3f065

**Comment by rhtyd** [comment]
@utchoang I tested latest master, and couldn't reproduce the issue; please re-open if I missed any case or the issue still exists. Thanks.

**Comment by utchoang** [comment]
@rhtyd With the exception of scrolling information, I've corrected some missing points in the auto-selection section when turning pages in each section (When turning pages, the auto-select is not correct). I will remove the roll, can you check and merge it for me, please?

**Comment by rhtyd** [comment]
@utchoang alright please merge latest master and let me know when it's ready for review/testing. Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang can you test against the Primate QA server (http://primate-qa.cloudstack.cloud:8080/client/pr/401/#/action/deployVirtualMachine)
- On searching the page number should reset to 1 for the selection/step
- We've stopped showing the cpu number/ram etc?
- Affinity groups gets empty after I click the next page

Please test it thoroughly against Primate QA server and/or any local setup and ping me when you're done. Thanks.

**Comment by utchoang** [comment]
@rhtyd I've completed fixed it. About the issue "Affinity groups get empty after clicking the next page". I don't understand why when I called listAffinityGroups, the API responded with count > item length result (bellow image). Thanks.
image

**Comment by rhtyd** [comment]
@shwstppr - can you check if this is an issue with the backend API implementation; i.e. wrong count is sent for the API response (if yes, please send a PR to apache/cloudstack targetting 4.13 branch). cc @davidjumani

**Comment by rhtyd** [comment]
@utchoang can you fix the conflict? Thanks.

**Comment by utchoang** [comment]
@rhtyd I've resolved it. Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
> @shwstppr - can you check if this is an issue with the backend API implementation; i.e. wrong count is sent for the API response (if yes, please send a PR to apache/cloudstack targetting 4.13 branch). cc @davidjumani

@utchoang https://github.com/apache/cloudstack/pull/4154 should solve the wrong count issue for AG

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@utchoang @svenvogel can you check on the above env, run a full end-to-end VM deployment wizard test ? Thanks.

Deployment wizard fails for me:
```
TypeError: Cannot read property 'keyboardOptions' of undefined
    at o.keyboardSelectOptions (DeployVM.vue:685)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.evaluate (vue.runtime.esm.js:4584)
    at o.keyboardSelectOptions (vue.runtime.esm.js:4836)
    at o.s (DeployVM.vue?c94a:10)
    at o.e._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554)
    at Xn (vue.runtime.esm.js:4310)
it @ vue.runtime.esm.js:8
rt @ vue.runtime.esm.js:8
tt @ vue.runtime.esm.js:8
e._render @ vue.runtime.esm.js:8
r @ vue.runtime.esm.js:8
nr.get @ vue.runtime.esm.js:8
nr.run @ vue.runtime.esm.js:8
Xn @ vue.runtime.esm.js:8
(anonymous) @ vue.runtime.esm.js:8
lt @ vue.runtime.esm.js:8
Promise.then (async)
at @ vue.runtime.esm.js:8
pt @ vue.runtime.esm.js:8
er @ vue.runtime.esm.js:8
nr.update @ vue.runtime.esm.js:8
ve.notify @ vue.runtime.esm.js:8
set @ vue.runtime.esm.js:8
setState @ chunk-vendors.e4a86834.js:74
setOpenState @ moment.js:5621
onMenuSelect @ moment.js:5621
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
__emit @ chunk-vendors.e4a86834.js:74
onClick @ moment.js:5621
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
__emit @ chunk-vendors.e4a86834.js:74
onClick @ chunk-vendors.e4a86834.js:1
click @ chunk-vendors.e4a86834.js:1
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
__emit @ chunk-vendors.e4a86834.js:74
onClick @ index.js:1
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
Qi.a._wrapper @ vue.runtime.esm.js:8
vue.runtime.esm.js:1888 TypeError: Cannot read property 'keyboardOptions' of undefined
    at o.keyboardSelectOptions (DeployVM.vue:685)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.evaluate (vue.runtime.esm.js:4584)
    at o.keyboardSelectOptions (vue.runtime.esm.js:4836)
    at o.s (DeployVM.vue?c94a:10)
    at o.e._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554)
    at Xn (vue.runtime.esm.js:4310)
it @ vue.runtime.esm.js:8
rt @ vue.runtime.esm.js:8
tt @ vue.runtime.esm.js:8
e._render @ vue.runtime.esm.js:8
r @ vue.runtime.esm.js:8
nr.get @ vue.runtime.esm.js:8
nr.run @ vue.runtime.esm.js:8
Xn @ vue.runtime.esm.js:8
(anonymous) @ vue.runtime.esm.js:8
lt @ vue.runtime.esm.js:8
Promise.then (async)
at @ vue.runtime.esm.js:8
pt @ vue.runtime.esm.js:8
er @ vue.runtime.esm.js:8
nr.update @ vue.runtime.esm.js:8
e.$forceUpdate @ vue.runtime.esm.js:8
(anonymous) @ chunk-207263fb.6225f06d.js:1
(anonymous) @ lodash.js:1
(anonymous) @ lodash.js:1
Ti @ lodash.js:1
(anonymous) @ lodash.js:1
ra @ lodash.js:1
pl @ lodash.js:1
(anonymous) @ chunk-207263fb.6225f06d.js:1
(anonymous) @ lodash.js:1
(anonymous) @ lodash.js:1
Ti @ lodash.js:1
(anonymous) @ lodash.js:1
ra @ lodash.js:1
pl @ lodash.js:1
(anonymous) @ chunk-207263fb.6225f06d.js:1
Promise.then (async)
fetchOptions @ chunk-207263fb.6225f06d.js:1
(anonymous) @ chunk-207263fb.6225f06d.js:1
(anonymous) @ lodash.js:1
Ti @ lodash.js:1
(anonymous) @ lodash.js:1
cl @ lodash.js:1
onSelectZoneId @ chunk-207263fb.6225f06d.js:1
Object.keys.forEach.l.<computed> @ moment.js:5621
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
nt @ vue.runtime.esm.js:8
Tn.e.$emit @ vue.runtime.esm.js:8
fireChange @ moment.js:5621
onMenuSelect @ moment.js:5621
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
__emit @ chunk-vendors.e4a86834.js:74
onClick @ moment.js:5621
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
__emit @ chunk-vendors.e4a86834.js:74
onClick @ chunk-vendors.e4a86834.js:1
click @ chunk-vendors.e4a86834.js:1
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
__emit @ chunk-vendors.e4a86834.js:74
onClick @ index.js:1
nt @ vue.runtime.esm.js:8
n @ vue.runtime.esm.js:8
Qi.a._wrapper @ vue.runtime.esm.js:8
vue.runtime.esm.js:1888 TypeError: Cannot read property 'keyboardOptions' of undefined
    at o.keyboardSelectOptions (DeployVM.vue:685)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.evaluate (vue.runtime.esm.js:4584)
    at o.keyboardSelectOptions (vue.runtime.esm.js:4836)
    at o.s (DeployVM.vue?c94a:10)
    at o.e._render (vue.runtime.esm.js:3548)
    at o.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
```

**Comment by rhtyd** [comment]
@utchoang another issue:
- When ISO is selected the user must select a disk offering (for the root disk), but no thank you is selected

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
