### PR TITLE
deployvm: Hiding networks for basic zones

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes passing `networkid` while tyring to deploy VMs in a basic zone as well as hides it in the deployVM form

Screenshot from 2020-11-18 17-08-57

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]
LGTM, needs a bit of testing

**Pull request merged**
