### PR TITLE
view: add custom new account form

### LINKED ISSUE #238: [BUG] Identify and Access > Accounts > New account - 'Domain' and 'Role' must be mandatory fields
**Describe the bug**
It's not possible to create account without entering 'Domain' and 'Role' so they must be mandatory, as in the old UI.

**To Reproduce**
1. Go to 'Identify and Access > Accounts' and click on 'Add account'. 

**Expected behavior**
'Domain' and 'Role' fields must be mandatory, as in the old UI.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None

### LINKED ISSUE #240: [BUG] Domain admin: Identify and access > Roles should not be visible
**Describe the bug**
'Identify and access > Roles' screen is visible but the domain admin has no access there so it doesn't make sense.

**To Reproduce**
1. Log in as domain admin, go to 'Identify and access > Roles'

**Expected behavior**
'Identify and access > Roles' should not be visible when logged as domain admin.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
None.

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #238 

Screenshot from 2020-04-13 14-41-10

### CODE REVIEW

**Comment by shwstppr** [comment]
@rhtyd can be reviewed depending upon the comment on the original issue

**Comment by rhtyd** [comment]
@shwstppr or @davidjumani  can you fix the conflict? Thanks.

**Comment by shwstppr** [comment]
@rhtyd done

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
Closing in favour of #170

**Pull request closed without merging**
