### PR TITLE
Select/checked row when clicking anywhere on the line table

### LINKED ISSUE #721: [FEATURE] Clicking anywhere on the line (instead of just the radio button) should select the i.e. Offering
image

I would like to be able to click anywhere on the line in order to select the offering - instead of having to click only the "radio button"

### PR DESCRIPTION
**Pull request by utchoang**
@rhtyd cc @svenvogel 
Fixes #721

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@utchoang For some reason selecting disk offering breaks when not clicking on the radio button

**Comment by utchoang** [comment]
@rhtyd @davidjumani cc @svenvogel Please review it. Thanks.

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM! Thanks @utchoang 
@rhtyd Good to go!

**Pull request merged**
