### PR TITLE
Fix ListResourceTable

### LINKED ISSUE #512: New list resource tab does not do pagination and refresh on parent resource refresh
@davidjumani please address for the new list resource tab used in vmsnapshots/backups tabs for VM instance:
- Add a watch on resource, refresh the view if parent resource changes (i.e. refresh button)
- Add pagination option for the API (see rick account in primate-QA which has over 35 backups for testing)

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #512 

Backups do not support search by id, so hiding the search bar

Screenshot from 2020-07-08 01-11-28

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM

**Pull request merged**
