### PR TITLE
[FIX] VM Deployment Wizard Changes

### PR DESCRIPTION
**Pull request by utchoang**
Open for https://github.com/apache/cloudstack-primate/issues/306
@rhtyd cc @svenvogel 
* [x] Template filter can be left to search box and not working
* [x] TBD: should we add/have a way to add network, re-use the add network form perhaps?
* [x] Not able to specify a new group
~~* [x] Hypervisor option could be moved next to zone?~~
* [x] Changing default network has no effect
* [x] Do validation for form elements, looks like only zone is validated; but say service offering is not
* [x] Group ID passed instead of name in the deployVM API
* [x] Show Password after deploying VM

### CODE REVIEW

**Comment by utchoang** [comment]
* Move template/iso filter to left of search box
image

**Comment by utchoang** [comment]
Hi @rhtyd I have some questions:
1. For adding new network, do you mean you want to make it similar to the first version? (add networking in a network section)
2. Change default network: According to https://github.com/apache/cloudstack/blob/ef14e195c4b40be53466f081e4632547aa0cf43c/ui/scripts/instanceWizard.js#L1227. I found that in the old UI, the default network selected as will be ordered first in the list of network for send to server. Do you have any other requirements?

**Comment by utchoang** [comment]
@rhtyd Can you answer my questions?

**Comment by rhtyd** [comment]
@utchoang leave that network part, I'll handle that. Thanks.

**Comment by shwstppr** [comment]
@utchoang @rhtyd when there are no VPCs

```
NetworksCreation.vue?733d:167 Uncaught (in promise) TypeError: Cannot read property 'unshift' of undefined
    at eval (VM3349 NetworksCreation.vue:194)
```

**Comment by utchoang** [comment]
@rhtyd @shwstppr 
Travis could not build successfully due to an error received:
image

**Comment by rhtyd** [comment]
Travis may pass in next run.
@utchoang can you have a look at #51

**Comment by utchoang** [comment]
Hi @rhtyd I added the show password after deploy VM based on https://github.com/apache/cloudstack/blob/master/ui/scripts/instanceWizard.js#L1447. But I haven't tested it because I don't know how to do it. Please test me and give me your opinion if any.

**Comment by rhtyd** [comment]
thanks @utchoang I'll test and merge this

**Comment by svenvogel** [comment]
@rhtyd could you find some time to check this? :)

**Comment by rhtyd** [comment]
Yes it's on my radar @svenvogel

**Pull request merged**
