### PR TITLE
VM Hardware: NICs and IPs management 

### PR DESCRIPTION
**Pull request by RitchieVincent**
#58

### CODE REVIEW

**Comment by RitchieVincent** [comment]
@rhtyd I've updated the async poll function to be inside a global plugin found in `src/utils/plugins.js`. If you're happy with that way of doing things let me know, and I can refactor the old methods to use this way.

**Comment by rhtyd** [comment]
Thanks @RitchieVincent, I'll review and test, and get back to you.

**Comment by rhtyd** [comment]
@RitchieVincent please ping me once you've fixed the conflicts and addressed the poll/refactorings

**Comment by rhtyd** [comment]
@RitchieVincent kindly follow the fixes, avoid passing `response: json` to API, which is handled centrally. Otherwise LGTM, made some fixes, will merge it now.

**Pull request merged**
