### PR TITLE
Identify and access - Add user - duplicated password field

### PR DESCRIPTION
**Pull request by utchoang**
@rhtyd cc @svenvogel 
Fixes https://github.com/apache/cloudstack-primate/issues/175. Please review and let me your comment.
image
image

### CODE REVIEW

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel 
I've completed fixes duplicated password field on "add user" and "add account". Please review and let me your comment.
image
image

**Comment by shwstppr** [comment]
@utchoang can you please resolve the conflict

**Comment by utchoang** [comment]
@shwstppr I've resolved conflict. Thanks.

**Comment by shwstppr** [comment]
@rhtyd ready for review

**Comment by rhtyd** [comment]
@utchoang can you fix the conflict? Thanks.

**Comment by shwstppr** [comment]
@rhtyd this can be reviewed and merged. We will need a custom form for Add Account but this will be useful for Add User

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
