### PR TITLE
VM deployment form group template/iso

### PR DESCRIPTION
**Pull request by utchoang**
Open for https://github.com/apache/cloudstack-primate/issues/468

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@rhytd I think if the group template/iso by the featured, community, ... the old filter in the search bar will be removed, right?
image

**Comment by rhtyd** [comment]
Yes @utchoang there is no need of that filtering now, just a search is OK

**Comment by utchoang** [comment]
@rhtyd cc @svenvogel I've completed this task. Please review it. Thanks.
image

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Pull request merged**
