### PR TITLE
FIX - Network - Remove the required account in creating a network

### LINKED ISSUE #826: [BUG]  Creating network via the Depoy VM wizard - requires account id?
If not mistaken, this should NOT be required?

image

### PR DESCRIPTION
**Pull request by utchoang**
Fixes #826 
@rhtyd cc @svenvogel 
image

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
@blueorangutan package

**Review by GabrielBrascher — COMMENTED** [review]
@utchoang thanks for the PR.
I noticed that when creating a guest network of type L2 the Account field is not presented.

image

Tested on: http://primate-qa.cloudstack.cloud:8080/client/pr/830 (JID-3620)

**Comment by utchoang** [comment]
@GabrielBrascher Account field will visible when Domain is selected. Thanks.

**Comment by GabrielBrascher** [comment]
Aha, perfect!

it works indeed, thanks @utchoang!

**Review by GabrielBrascher — APPROVED** [review]
LGTM

**Review by davidjumani — APPROVED** [review]
LGTM Thanks @utchoang

**Pull request merged**
