### PR TITLE
Handle redirect to sub menu when click parent menu

### LINKED ISSUE #805: [FEATURE] Clicking Menu group name - to choose the first menu item
For some time now, while testing and having to click around frequently, I've been very irritated by having to click on Compute, then on Instances (in order to reach Instances as the first menu item), as this means clicking 2 times in order to get to the first item in the menu group - this is not user/mouse friendly :)

Can we somehow ensure old-UI-like behaviour -  that when a menu group (i.e 'Compute' or 'Images') is clicked, that we automatically select/show the first menu item (i.e. 'Instances', or 'Templates' in this example).

Hopefully it makes sense. thx

### PR DESCRIPTION
**Pull request by utchoang**
Fixes #805 
@rhtyd cc @svenvogel Please review it. Thanks.

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
I still see the same old behaviour @utchoang can you check the test/QA env.

**Comment by utchoang** [comment]
@rhtyd Currently, it only activity for the tablet and mobile mode.

**Comment by rhtyd** [comment]
@utchoang can you do this for desktop as well?

**Comment by utchoang** [comment]
@blueorangutan  package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Thanks @utchoang I tested does not seem to work, is there something I'm missing (I'm expecting the VM to be selected/open when I click compute)?

**Comment by utchoang** [comment]
@rhtyd Sorry about my mistake. Please review it again. Thanks.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Tested few screens for mobile and desktop - lgtm.

**Comment by davidjumani** [comment]
@utchoang It intermittently works on desktops. Just navigate from top to bottom and back up again and sometimes it does not open the first sub-menu. Could you fix it ?

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM, @davidjumani are you lgtm on it for merging?

**Comment by davidjumani** [comment]
@utchoang Looks like navigation sometimes breaks now if anything other than the first sub-menu item is selected :(

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM - on latest testing on desktop and mobile; the only case it doesn't work is when you click on right on the nav title (not on the expand button but between the title/label and the right expand button, it expands than open the first child) - still better than what we've now.
@davidjumani can you test your cases?

**Review by davidjumani — APPROVED** [review]

**Comment by davidjumani** [comment]
@utchoang @rhtyd Works well on mobile and tablet. Clicking the icon / text while on desktop opens the first submenu, so users who'd just like to brows the navbar can click the blank space

**Pull request merged**
