### PR TITLE
Some Spanish translations

### PR DESCRIPTION
**Pull request by nvazquez**
**Work in progress**

Add missing translations in Spanish.

Views to translate - PRs adding internationalization where missing:

- [x] Login page (#494)
- [x] Dashboard (#494)
- [ ] Compute
   - [x] Instances (#493 - #514)
   - [x] Instance groups (#515)
   - [x] SSH Key Pairs (nothing to add)
   - [ ] Affinity Groups
- [ ] Storage
   - [ ] Volumes
   - [ ] Snapshots
   - [ ] VM Snapshots
   - [ ] Backups
- [ ] Network
   - [ ] Guest networks
   - [ ] VPC
   - [ ] Security Groups
   - [ ] Public IP Addresses
   - [ ] VPN Customer Gateway
- [ ] Images
   - [ ] Templates
   - [ ] ISOs
- [ ] Events
- [ ] Projects
- [ ] Accounts
- [ ] Domains
- [ ] Roles
- [ ] Infrastructure
- [ ] Service Offerings
- [ ] Configuration

### CODE REVIEW

**Comment by rhtyd** [comment]
@nvazquez please follow https://github.com/apache/cloudstack-primate/pull/481 you or the other PR may cause conflicts for each other. Also please merge latest master, the drafts does not show if a PR has conflicts, until you click ready for review.

**Comment by nvazquez** [comment]
Copy that - thanks @rhtyd. I'm creating separate PRs for parts that were missing translation keys and leaving this PR to Spanish translations only

**Comment by rhtyd** [comment]
@nvazquez ping - will we be able to finish this PR towards 1.0/GA milestone or should we move this to 1.1?

**Comment by rhtyd** [comment]
Tentatively moved to 1.1 as I see many outstanding tasks

**Comment by nvazquez** [comment]
@rhtyd the missing items can be moved to 1.1 but I think this one can be merged

**Comment by rhtyd** [comment]
Merging this based on @nvazquez 's comments; any more changes can be submitted by a new PR

**Pull request merged**
