### PR TITLE
Resource download popup

### PR DESCRIPTION
**Pull request by RitchieVincent**

### CODE REVIEW

**Comment by rhtyd** [comment]
@RitchieVincent does this also handle/implement download option for all the - template, isos and volume?

**Comment by RitchieVincent** [comment]
> @RitchieVincent does this also handle/implement download action for - template, isos and volume?

Yes if you see the files `src/config/section/image.js` and `src/config/section/storage.js`, it passes the correct url in to the notification.

**Comment by rhtyd** [comment]
@RitchieVincent okay, I'll test it shortly.

**Comment by rhtyd** [comment]
@RitchieVincent please follow the change on master in https://github.com/apache/cloudstack-primate/commit/e7b0a2b9adb9e569bdf43a17d9c3771e76b8c3c2
I had to ultimately redo the implementation - we basically wanted a way to custom how we want to display the response.

**Pull request closed without merging**
