### PR TITLE
view: remove treeview item on delete

### LINKED ISSUE #180: [BUG] Identify and access > Domains > delete domain does not remove it from the tree
**Describe the bug**
When you delete a domain in 'Identify and access > Domains' it does not remove it from the tree even though it's actually deleted.

**To Reproduce**
1. Go to 'Identify and access > Domains' and select a domain
2. Click on 'Delete domain' icon and confirm the operations. 
3. Look at the domain tree - it's still there. If you try to click on the deleted domain, it's not shown though.

**Expected behavior**
The deleted domain should be removed from the domain tree.

**Screenshots**
None

**Desktop (please complete the following information):**
- OS: Windows 10 Pro x64
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Additional context**
None

### PR DESCRIPTION
**Pull request by shwstppr**
Fixes #180

### CODE REVIEW

**Comment by rhtyd** [comment]
Dupes https://github.com/apache/cloudstack-primate/pull/219

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack-primate/pull/219 was complex, reopened

**Comment by rhtyd** [comment]
ping @shwstppr are you working on this, the other PR is bit complex - can you either finish this or review/fix the other one, thanks.

**Comment by shwstppr** [comment]
@rhtyd will review by eod. Slight improvement in behaviour I wanted is that after delete UI moves to parent though with current changes it can only move closest item before the current one and the tree view is not showing the new item as selected (highlighted in blue color)

**Comment by shwstppr** [comment]
@rhtyd #219 didn't worked for me, tested manually.

This one works but with few limitations as mentioned above. Main issue: item not shown highlighted in UI as it is below screen
Screenshot from 2020-04-07 12-15-58

**Pull request closed without merging**
