### PR TITLE
FIX - Changing project no longer changes the sidebar background/theme

### LINKED ISSUE #820: [BUG] Changing project no longer changes the sidebar background/theme
On latest master, create a project and select the project to switch to the new project. On changing to a project, the sidebar is not longer dark. Was there a new config setting to enforce/change this @utchoang ?

### PR DESCRIPTION
**Pull request by utchoang**
Fixes #820 
- Default View:
image

- Project View:
image

### CODE REVIEW

**Comment by utchoang** [comment]
@blueorangutan package

**Comment by utchoang** [comment]
@rhtyd @davidjumani cc @svenvogel Please review it. Thanks.

**Review by davidjumani — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
@utchoang or @davidjumani can you send doc PR for https://github.com/apache/cloudstack-documentation/blob/master/source/installguide/primate.rst as well thanks.

**Pull request merged**
