### PR TITLE
Adding contextual info for resource status

### LINKED ISSUE #466: Usability: Explain what states mean
Different views have different states, for example VM in stopped/running states. In some views, for ex. the networks tab what states mean is not very obvious and may require enhancing the Status.vue component to detect which `$route.name` it is in to add some additional helper tooltip to explain what the state means (for example using the FSM state from backend code).

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #466 

Screenshot from 2020-07-02 11-01-19

Screenshot from 2020-07-02 11-09-45

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@PaulAngus Looks good ?

**Comment by rhtyd** [comment]
Ping @PaulAngus can you review

**Comment by PaulAngus** [comment]
I'd make 2 comments:

1. Can this be done in a way which uses the translation files?
2. Be careful of being too technical.  for instance, for VM 'Running "_host id has the host that it is running on_.". host_id means nothing to a _user_ and i'm not sure what it means to an operator... can a VM be on, and cloudstack **not** have a host_id ?

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
LGTM good work @davidjumani

**Pull request merged**
