### PR TITLE
Fixes for vapps

### PR DESCRIPTION
**Pull request by davidjumani**

### CODE REVIEW

**Comment by andrijapanicsb** [comment]
The order is still reversed vs what's shown in the vCenter:

image

**Comment by andrijapanicsb** [comment]
Licences are sorted nicely.

**Comment by andrijapanicsb** [comment]
LGTM with pass length, ordering of Eula and ordering of Configurations

**Comment by andrijapanicsb** [comment]
cpuspeed set to by default - LGTM

**Comment by andrijapanicsb** [comment]
New issue - described here: https://github.com/apache/cloudstack-primate/issues/618#issuecomment-682468769

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
so far so good
let's merge this one @davidjumani so that I can continue to log bug after that  (for the master ;) )

**Comment by davidjumani** [comment]
@blueorangutan package

**Pull request merged**
