### PR TITLE
Fixing ldap form

### LINKED ISSUE #112: [FEATURE] new ldap functionality
changes to the accountWizard since 4.14:
Screenshot 2020-01-15 at 10 30 36

a filter dropdown and a column for the source of a possible conflict

TBD

**Additional context**
LDAP has different levels of integration. all of which are readonly from a cloudstack point of view and which are not distinquished between from the ui at the moment.
Note that the newest, domain level account binding, depends on domain level settings.

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #112 
Requires https://github.com/apache/cloudstack/pull/4164 to list domain-specific LDAP configs

Screenshot from 2020-06-22 19-03-55

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd good to go!

**Comment by davidjumani** [comment]
@rhtyd good to go!

**Comment by davidjumani** [comment]
@rhtyd Right now, listLdapUsers does not support search or pagination

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani add information pop-over like other forms, add doc-link to the custom form (somewhere put a <a-icon for question and link to this.$config.docBase + ....)
Also test/check against old UI.

Primate API call runs:
```
domainid: 78ec0573-03fb-4c02-872a-b0f3a86471dc
roleid: 16919363-5fe0-11ea-9a56-1e006800018c
timezone: ACT
networkdomain: net-domain
group: group
username: ldapman
command: importLdapUsers
response: json
```

Legacy UI runs:
```
command: importLdapUsers
domainid: e4874e10-5fdf-11ea-9a56-1e006800018c
account: acount-name
roleid: 16919363-5fe0-11ea-9a56-1e006800018c
timezone: Pacific/Johnston
networkdomain: net-domain
group: ldap-group
response: json
```

Mismatch account not passed, instead username? Also, the label 'Group' should say 'LDAP Group'. Check the form against old UI.

**Comment by davidjumani** [comment]
@rhtyd In the legacy UI, although the default filter is 'No Filter', the initial listLdapUsrers call uses 'Any Domain' as its filter. In this case, using 'No Filter' for the initial listLdapUsrers call. Should I change it to match the legacy UI ?

**Comment by rhtyd** [comment]
@davidjumani can you discuss with @DaanHoogland ?

**Comment by davidjumani** [comment]
Discussed with @DaanHoogland Good to go!

**Comment by DaanHoogland** [comment]
looks good

**Pull request merged**
