### PR TITLE
[WIP] Added core-js@3 dependency

### LINKED ISSUE #11: Runtime issues due incompatible core-js dependency
When running primate CentOS 7/Node 10.17.0 using the dependency installation instruction in the README, it will fail during webpack or startup due to an incompatible core-js dependency.

It is necessary to install core-js@3 to make primate work. This should either be added to the npm dependencies or to the README (if global installation is required).

The error trace is below:
```
npm[84683]: ERROR  Failed to compile with 220 errors6:53:01 PM
npm[84683]: These dependencies were not found:
npm[84683]: * core-js/modules/es.array.concat in ./src/permission.js, ./src/components/menu/menu.js and 2 others
npm[84683]: * core-js/modules/es.array.filter in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/UserMenu.vue?vue&type=script&lang=js& and 10 others
npm[84683]: * core-js/modules/es.array.find in ./src/components/menu/menu.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/page/GlobalLayout.vue?vue&type=script&lang=js& and 3 others
npm[84683]: * core-js/modules/es.array.find-index in ./src/utils/helper/permission.js
npm[84683]: * core-js/modules/es.array.for-each in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/UserMenu.vue?vue&type=script&lang=js& and 12 others
npm[84683]: * core-js/modules/es.array.includes in ./src/permission.js, ./src/components/menu/menu.js and 12 others
npm[84683]: * core-js/modules/es.array.index-of in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/ProjectMenu.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/multitab/MultiTab.vue?vue&type=script&lang=js& and 2 others
npm[84683]: * core-js/modules/es.array.map in ./src/components/menu/menu.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/multitab/MultiTab.vue?vue&type=script&lang=js& and 3 others
npm[84683]: * core-js/modules/es.array.reverse in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/HeaderNotice.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.array.slice in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/widgets/Status.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.array.sort in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/AutogenView.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/compute/InstanceHardware.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.array.splice in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/dashboard/UsageDashboard.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.date.to-string in ./src/utils/util.js, ./src/utils/filter.js
npm[84683]: * core-js/modules/es.function.name in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/ProjectMenu.vue?vue&type=script&lang=js& and 13 others
npm[84683]: * core-js/modules/es.number.constructor in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/widgets/ChartCard.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.number.to-fixed in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/view/InfoCard.vue?vue&type=script&lang=js&, ./src/config/section/compute.js and 2 others
npm[84683]: * core-js/modules/es.object.get-own-property-descriptor in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/UserMenu.vue?vue&type=script&lang=js& and 7 others
npm[84683]: * core-js/modules/es.object.get-own-property-descriptors in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/UserMenu.vue?vue&type=script&lang=js& and 7 others
npm[84683]: * core-js/modules/es.object.keys in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/UserMenu.vue?vue&type=script&lang=js& and 9 others
npm[84683]: * core-js/modules/es.object.to-string in ./src/api/index.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/ProjectMenu.vue?vue&type=script&lang=js& and 18 others
npm[84683]: * core-js/modules/es.parse-float in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/view/InfoCard.vue?vue&type=script&lang=js&, ./src/config/section/compute.js and 2 others
npm[84683]: * core-js/modules/es.regexp.exec in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/PageView.vue?vue&type=script&lang=js&, ./src/locales/index.js and 4 others
npm[84683]: * core-js/modules/es.regexp.to-string in ./src/utils/filter.js
npm[84683]: * core-js/modules/es.set in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/AutogenView.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.string.includes in ./src/components/menu/menu.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/multitab/MultiTab.vue?vue&type=script&lang=js& and 5 others
npm[84683]: * core-js/modules/es.string.iterator in ./src/api/index.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/ProjectMenu.vue?vue&type=script&lang=js& and 4 others
npm[84683]: * core-js/modules/es.string.match in ./src/locales/index.js
npm[84683]: * core-js/modules/es.string.replace in ./src/utils/filter.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/AutogenView.vue?vue&type=script&lang=js& and 1 other
npm[84683]: * core-js/modules/es.string.search in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/PageView.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.string.split in ./src/utils/helper/permission.js
npm[84683]: * core-js/modules/es.string.starts-with in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/AutogenView.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/compute/DeployVM.vue?vue&type=script&lang=js&
npm[84683]: * core-js/modules/es.symbol in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/HeaderNotice.vue?vue&type=script&lang=js& and 14 others
npm[84683]: * core-js/modules/es.symbol.description in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/ProjectMenu.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/HeaderNotice.vue?vue&type=script&lang=js& and 6 others
npm[84683]: * core-js/modules/es.symbol.iterator in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/ProjectMenu.vue?vue&type=script&lang=js&, ./src/config/router.js and 3 others
npm[84683]: * core-js/modules/web.dom-collections.for-each in ./src/permission.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/UserMenu.vue?vue&type=script&lang=js& and 12 others
npm[84683]: * core-js/modules/web.dom-collections.iterator in ./src/api/index.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/header/HeaderNotice.vue?vue&type=script&lang=js& and 6 others
npm[84683]: * core-js/modules/web.url in ./src/api/index.js
npm[84683]: To install them, you can run: npm install --save core-js/modules/es.array.concat core-js/modules/es.array.filter core-js/modules/es.array.find core-js/modules/es.array.find-index core-js/modules/es.array.for-each core-js/modules/es.array.includes core-js/modules/es.array.index-of core-js/modules/es.array.map core-js/modules/es.array.reverse core-js/modules/es.array.slice core-js/modules/es.array.sort core-js/modules/es.array.splice core-js/modules/es.date.to-string core-js/modules/es.function.name core-js/modules/es.number.constructor core-js/modules/es.number.to-fixed core-js/modules/es.object.get-own-property-descriptor core-js/modules/es.object.get-own-property-descriptors core-js/modules/es.object.keys core-js/modules/es.object.to-string core-js/modules/es.parse-float core-js/modules/es.regexp.exec core-js/modules/es.regexp.to-string core-js/modules/es.set core-js/modules/es.string.includes core-js/modules/es.string.iterator core-js/modules/es.string.match core-js/modules/es.string.replace core-js/modules/es.string.search core-js/modules/es.string.split core-js/modules/es.string.starts-with core-js/modules/es.symbol core-js/modules/es.symbol.description core-js/modules/es.symbol.iterator core-js/modules/web.dom-collections.for-each core-js/modules/web.dom-collections.iterator core-js/modules/web.url
```

### PR DESCRIPTION
**Pull request by onitake**
Fixes #11 .

**TODO** Still needs to be tested.

### CODE REVIEW

**Comment by rhtyd** [comment]
@onitake can you check, Travis is failing. You probably need to run npm install and commit the package lock file.

**Comment by onitake** [comment]
Yes, I thought as much.
I haven't had time to test it on my test instance yet, will do that today.

**Comment by rhtyd** [comment]
Created a new PR based on this PR @onitake cc @GabrielBrascher

**Comment by onitake** [comment]
Closing in favour of #16

**Pull request closed without merging**
