### PR TITLE
Display IP address while deleting it

### PR DESCRIPTION
**Pull request by ravening**
While deleting an IP address, the status message displays "Undefined" instead of IP.

Screenshot 2020-11-20 at 16 03 05

Navigate to Networks -> Public IP address -> Select any public ip -> Click delete button on top right

After the fix

Screenshot 2020-11-20 at 16 04 31

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Review by davidjumani — APPROVED** [review]
LGTM

**Comment by wido** [comment]
Advanced Networking also supports IPv6. Shouldn't that be shown here as well?

**Comment by rhtyd** [comment]
@wido can you test and raise a PR?

**Pull request merged**
