### PR TITLE
Adding custom Vue to change the vm service offering

### LINKED ISSUE #381: Create action component for changing VM service offering
Implement a new custom action component for changing service offering which can show details/options like the old UI when a VM (stopped or running) is scaled up (or service offering is changed):

Screenshot from 2020-06-05 10-38-30

This should also honour whether the compute offering is custom, unconstraint vs constraint. 

cc @davidjumani we can discuss with @shwstppr for advise

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes #381 

Screenshot from 2020-06-24 09-40-01
Screenshot from 2020-06-24 09-40-12

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd Could you check how to get the input in the form to be the proper length? Otherwise all good to go!

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@rhtyd good to go!

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@davidjumani pl fix conflict

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@shwstppr can you review and help test this, compare against legacy UI? I found some issues but I'm not sure if that's because of simulator. Perhaps when VM is stopped we should call changeServiceOffering API (otherwise, at least for Simulator it fails, possibly others hypervisors?)

**Comment by rhtyd** [comment]
Investigate if we can safely use the changeSer.... instead of scale... API for a stopped VM (for all hypervisors?); then fix the UI component to change the API depending on state

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@shwstppr can you review and test please?

**Pull request merged**
